import { execFileSync } from "node:child_process";
import { accessSync, constants, readFileSync, writeFileSync, unlinkSync, mkdirSync, statSync } from "node:fs";
import { delimiter, join } from "node:path";
import { getConfigDir } from "../config";
import { resolveAutoContext, type AutoContextMode } from "../claude/context-windows";
import { PROXY_MARKER, defaultAuthDetectDeps, detectClaudeAuth, ownAdmissionTokens, type AuthDetectDeps } from "../claude/auth-detect";
import { resolveClaudeAuthMode } from "../claude/auth-mode";
import { ANTHROPIC_PARENT_ENV_SLOTS, trustedNodeLauncherContext, type AnthropicParentEnvSlot } from "../cli/launcher-context";
import { isProxyAdmissionSecret } from "./auth-cors";
import type { OcxConfig } from "../types";
import { recordOwnedConfigPath } from "../lib/config-ownership";
import { providerContextCap } from "../providers/context-cap";
import { OPENAI_CODEX_PROVIDER_ID } from "../providers/openai-tiers";

/**
 * Does the opencodex dummy marker belong in the system environment?
 *
 * Keyed on the SAME resolver `ocx claude` uses, so an auto config with no Claude auth
 * also reaches plain `claude` launches — before this, auto-absent users got nothing
 * from auto-connect and the feature looked broken for exactly the people it helps
 * (devlog 260726_claude_auth_auto/035).
 *
 * NOTE this is a SNAPSHOT: the file only changes when this runs (proxy start, `ocx
 * ensure`, or a settings save). `ocx claude` re-resolves live on every launch.
 */
export type SystemEnvDeps = {
  /** Test seam; production uses the authenticated Node-launcher context. */
  preBunAnthropicSlots?: readonly AnthropicParentEnvSlot[] | null;
  /** Test seam for auth sources; `env` and `ownTokens` stay bound below. */
  authDetect?: Omit<Partial<AuthDetectDeps>, "env" | "ownTokens">;
};

/**
 * Bun may synthesize Anthropic variables from a project `.env` before this module runs.
 * Only values recorded by the plain-Node launcher are trusted as parent exports. Direct
 * Bun/service launches have no proof-bound slot list, so they fail closed and let the
 * file/keychain auth sources decide instead of allowing dotenv to select subscription mode.
 */
function systemEnvAnthropicEnv(
  env: NodeJS.ProcessEnv,
  preBunAnthropicSlots: readonly AnthropicParentEnvSlot[] | null | undefined,
): NodeJS.ProcessEnv {
  const trustedSlots = preBunAnthropicSlots === undefined
    ? trustedNodeLauncherContext()?.anthropicEnvSlots ?? []
    : preBunAnthropicSlots ?? [];
  const exported = new Set<AnthropicParentEnvSlot>(trustedSlots);
  const sanitized = { ...env };
  for (const name of ANTHROPIC_PARENT_ENV_SLOTS) {
    if (sanitized[name] !== undefined && !exported.has(name)) delete sanitized[name];
  }
  return sanitized;
}

function systemEnvMarkerMode(config: OcxConfig, deps: SystemEnvDeps = {}): "proxy" | "subscription" {
  const env = systemEnvAnthropicEnv(process.env, deps.preBunAnthropicSlots);
  const ownTokens = ownAdmissionTokens(config);
  return resolveClaudeAuthMode(config, detectClaudeAuth({
    ...defaultAuthDetectDeps(env, ownTokens),
    ...(deps.authDetect ?? {}),
    env: () => env,
    ownTokens,
  })).markerMode;
}

// ---------------------------------------------------------------------------
// Shell-hook env file: written on inject, sourced by the shell hook in .zshrc.
// This works for ALL new shells immediately, unlike launchctl setenv which only
// reaches processes launched directly by launchd (not Terminal.app children).
// ---------------------------------------------------------------------------

export function getShellEnvFilePath(): string {
  return join(getConfigDir(), "claude-env.sh");
}

function shellValue(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

function writeShellEnvFile(
  port: number,
  config: OcxConfig,
  modelEnv: Record<string, string> = {},
  auto?: AutoContextMode,
  deps: SystemEnvDeps = {},
): void {
  const lines = [
    `# Generated by opencodex — do not edit manually`,
    `export ANTHROPIC_BASE_URL=${shellValue(`http://127.0.0.1:${port}`)}`,
    `export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY=${shellValue("1")}`,
  ];
  // New lever keys are CONDITIONAL exports (audit 139 R2#1): a value the user already
  // exported in their shell wins even though launchctl knows nothing about it.
  const conditional = (name: string, value: string) =>
    `[ -z "\${${name}+x}" ] && export ${name}=${shellValue(value)}`;
  if (systemEnvMarkerMode(config, deps) === "proxy") {
    if (config.apiKeys?.length) {
      lines.push(`export ANTHROPIC_AUTH_TOKEN=${shellValue(config.apiKeys[0].key)}`);
    } else {
      lines.push(conditional("ANTHROPIC_AUTH_TOKEN", PROXY_MARKER));
    }
  }
  // Model slots (default + tiers + legacy small-fast) with [1m] applied (devlog 260712 B2).
  if (modelEnv.ANTHROPIC_MODEL) {
    lines.push(`export ANTHROPIC_MODEL=${shellValue(modelEnv.ANTHROPIC_MODEL)}`);
  } else if (config.claudeCode?.model) {
    lines.push(`export ANTHROPIC_MODEL=${shellValue(config.claudeCode.model)}`);
  }
  for (const [name, value] of Object.entries(modelEnv)) {
    if (name === "ANTHROPIC_MODEL") continue;
    lines.push(conditional(name, value));
  }
  const maxCtx = config.claudeCode?.maxContextTokens;
  if (typeof maxCtx === "number" && Number.isFinite(maxCtx) && maxCtx > 0) {
    lines.push(conditional("CLAUDE_CODE_MAX_CONTEXT_TOKENS", String(Math.floor(maxCtx))));
    lines.push(conditional("DISABLE_COMPACT", "1"));
  }
  // Auto-context (devlog 260712 020): same contract as `ocx claude` / launchctl.
  const autoShell = auto ?? resolveAutoContext(config.claudeCode);
  if (autoShell.enabled) lines.push(conditional("CLAUDE_CODE_AUTO_COMPACT_WINDOW", String(autoShell.compactWindow)));
  if (config.claudeCode?.alwaysEnableEffort === true) {
    lines.push(conditional("CLAUDE_CODE_ALWAYS_ENABLE_EFFORT", "1"));
  }
  const shellEnvPath = getShellEnvFilePath();
  recordOwnedConfigPath(getConfigDir(), shellEnvPath);
  mkdirSync(getConfigDir(), { recursive: true, mode: 0o700 });
  writeFileSync(shellEnvPath, lines.join("\n") + "\n", { encoding: "utf8", mode: 0o600 });
}

function removeShellEnvFile(): void {
  try { unlinkSync(getShellEnvFilePath()); } catch { /* already gone */ }
}

// ---------------------------------------------------------------------------
// .zshrc hook auto-install: adds a one-liner that sources claude-env.sh.
// Idempotent — skips if the hook line already exists.
// ---------------------------------------------------------------------------

const SHELL_HOOK_MARKER = "# opencodex claude-env hook";
const SHELL_HOOK_LINE = `${SHELL_HOOK_MARKER}\n[ -f ~/.opencodex/claude-env.sh ] && source ~/.opencodex/claude-env.sh`;

export function installShellHook(): { installed: boolean; reason?: string } {
  if (process.platform !== "darwin") return { installed: false, reason: "not macOS" };
  const home = process.env.HOME;
  if (!home) return { installed: false, reason: "no HOME" };
  const zshrcPath = join(home, ".zshrc");
  try {
    let content = "";
    try { content = readFileSync(zshrcPath, "utf8"); } catch { /* file doesn't exist yet */ }
    if (content.includes(SHELL_HOOK_MARKER)) return { installed: false, reason: "already installed" };
    const addition = `\n${SHELL_HOOK_LINE}\n`;
    writeFileSync(zshrcPath, content + addition, { encoding: "utf8", mode: 0o644 });
    return { installed: true };
  } catch (err) {
    return { installed: false, reason: `write failed: ${err instanceof Error ? err.message : String(err)}` };
  }
}

export function uninstallShellHook(): { removed: boolean; reason?: string } {
  if (process.platform !== "darwin") return { removed: false, reason: "not macOS" };
  const home = process.env.HOME;
  if (!home) return { removed: false, reason: "no HOME" };
  const zshrcPath = join(home, ".zshrc");
  try {
    const content = readFileSync(zshrcPath, "utf8");
    if (!content.includes(SHELL_HOOK_MARKER)) return { removed: false, reason: "not installed" };
    // Match CR?LF, not LF alone. A .zshrc with CRLF line endings — ordinary on a home
    // directory an editor or another OS has touched — did not match, so the file was
    // rewritten unchanged and the caller was told the hook was removed. Reporting success
    // while the hook still sources on every new shell is the worse of the two failures.
    const cleaned = content.replace(/\r?\n?# opencodex claude-env hook\r?\n\[.*claude-env\.sh.*(?:\r?\n)?/g, "\n");
    // Verify instead of assuming: if the marker survives, the block is shaped in a way this
    // pattern does not own, and the honest answer is failure rather than a silent no-op.
    if (cleaned.includes(SHELL_HOOK_MARKER)) {
      return { removed: false, reason: "hook block present but not in the expected shape; remove it manually" };
    }
    writeFileSync(zshrcPath, cleaned, { encoding: "utf8", mode: 0o644 });
    return { removed: true };
  } catch (error) {
    if (error && typeof error === "object" && (error as { code?: unknown }).code === "ENOENT") {
      return { removed: false, reason: "not installed" };
    }
    return { removed: false, reason: "read/write failed" };
  }
}

/** Whether a real `claude` executable is discoverable from this process's PATH. */
export function claudeCodeCliInstalled(pathValue = process.env.PATH): boolean {
  if (!pathValue) return false;
  for (const directory of pathValue.split(delimiter)) {
    // An empty PATH segment means the current directory. Do not let the proxy treat a
    // workspace-local file as a durable user installation.
    if (!directory) continue;
    const candidate = join(directory, "claude");
    try {
      if (!statSync(candidate).isFile()) continue;
      accessSync(candidate, constants.X_OK);
      return true;
    } catch {
      // Keep scanning PATH after missing, non-file, and non-executable entries.
    }
  }
  return false;
}

/**
 * Keep the shell hook aligned with the integration that can actually consume it.
 * Claude Desktop uses its own profile and does not source `.zshrc`; this hook exists
 * only for plain Claude Code CLI launches.
 *
 * Reconciliation is PATH-sensitive by construction: "Claude Code is installed" is answered
 * from the PATH of whichever process calls this. A launchd/service context with a stripped
 * PATH can therefore fail to see a `claude` the user's interactive shell finds, and this will
 * remove the hook. That is the intended failure direction — removing an OpenCodex-owned block
 * is reversible on the next foreground `ocx start`, whereas leaving a hook pointing at an
 * uninstalled CLI is the stale state this reconciliation exists to clear. Only the block
 * carrying our own marker is ever touched; user lines are preserved.
 */
export function reconcileShellHook(systemEnvInjected: boolean): {
  changed: boolean;
  state: "installed" | "absent" | "failed";
  reason?: string;
} {
  if (process.platform !== "darwin") return { changed: false, state: "absent", reason: "not macOS" };
  if (systemEnvInjected && claudeCodeCliInstalled()) {
    const result = installShellHook();
    if (result.installed) return { changed: true, state: "installed" };
    if (result.reason === "already installed") {
      return { changed: false, state: "installed", reason: result.reason };
    }
    return { changed: false, state: "failed", reason: result.reason ?? "install failed" };
  }

  const result = uninstallShellHook();
  if (!result.removed && result.reason !== "not installed") {
    return { changed: false, state: "failed", reason: result.reason ?? "remove failed" };
  }
  return {
    changed: result.removed,
    state: "absent",
    reason: systemEnvInjected ? "Claude Code not installed" : "system environment inactive",
  };
}

const SYSTEM_ENV_NAMES = [
  "ANTHROPIC_BASE_URL",
  "CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY",
  "ANTHROPIC_AUTH_TOKEN",
] as const;

const MANAGED_SYSTEM_ENV_NAMES = new Set<string>([
  ...SYSTEM_ENV_NAMES,
  "ANTHROPIC_DEFAULT_OPUS_MODEL",
  "ANTHROPIC_DEFAULT_SONNET_MODEL",
  "ANTHROPIC_DEFAULT_FABLE_MODEL",
  "ANTHROPIC_DEFAULT_HAIKU_MODEL",
  "ANTHROPIC_SMALL_FAST_MODEL",
  "CLAUDE_CODE_MAX_CONTEXT_TOKENS",
  "DISABLE_COMPACT",
  "CLAUDE_CODE_AUTO_COMPACT_WINDOW",
  "CLAUDE_CODE_ALWAYS_ENABLE_EFFORT",
]);

interface SystemEnvTracking {
  pid: number;
  port: number;
  injectedAt: string;
  /** Keys that were actually set by injection (revert only unsets these). */
  injectedKeys?: string[];
}

type SystemEnvResult = { injected: boolean; reason?: string };
type RevertResult = { reverted: boolean; reason?: string };
type CleanupResult = { cleaned: boolean; reason?: string };

export function getSystemEnvTrackingPath(): string {
  return join(getConfigDir(), "system-env-port");
}

export function launchctlGetenv(name: string): string | undefined {
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return undefined;
  try {
    const value = execFileSync("/bin/launchctl", ["getenv", name], { encoding: "utf8" }).trim();
    return value || undefined;
  } catch {
    return undefined;
  }
}

function readTracking(): SystemEnvTracking | undefined {
  try {
    const tracking = JSON.parse(readFileSync(getSystemEnvTrackingPath(), "utf8")) as Partial<SystemEnvTracking>;
    if (!Number.isInteger(tracking.port) || typeof tracking.pid !== "number" || typeof tracking.injectedAt !== "string") {
      return undefined;
    }
    const injectedKeys = Array.isArray(tracking.injectedKeys)
      ? [...new Set(tracking.injectedKeys.filter(
        (name): name is string => typeof name === "string" && MANAGED_SYSTEM_ENV_NAMES.has(name),
      ))]
      : undefined;
    return { ...tracking, injectedKeys } as SystemEnvTracking;
  } catch {
    return undefined;
  }
}

function setLaunchctlEnv(name: string, value: string): void {
  execFileSync("/bin/launchctl", ["setenv", name, value]);
}

function unsetLaunchctlEnv(name: string): void {
  execFileSync("/bin/launchctl", ["unsetenv", name]);
}

function ownedBaseUrl(port: number): string {
  return `http://127.0.0.1:${port}`;
}

function writeTracking(port: number, injectedKeys: string[]): void {
  recordOwnedConfigPath(getConfigDir(), getSystemEnvTrackingPath());
  mkdirSync(getConfigDir(), { recursive: true, mode: 0o700 });
  writeFileSync(getSystemEnvTrackingPath(), JSON.stringify({
    pid: process.pid,
    port,
    injectedAt: new Date().toISOString(),
    injectedKeys,
  }), { encoding: "utf8", mode: 0o600 });
}

function rollbackInjectedKeys(port: number, injectedKeys: string[]): void {
  const rollbackFailed: string[] = [];
  for (const name of [...injectedKeys].reverse()) {
    try {
      unsetLaunchctlEnv(name);
    } catch {
      rollbackFailed.unshift(name);
    }
  }

  if (rollbackFailed.length > 0) {
    writeTracking(port, rollbackFailed);
    return;
  }

  try { unlinkSync(getSystemEnvTrackingPath()); } catch { /* already gone */ }
}

/**
 * In-process effective model-env (default + tier slots, [1m] applied) under the shared
 * 3s bound (audit R4#3). Returns {} on timeout/failure so injection degrades safely.
 */
async function computeEffectiveModelEnv(config: OcxConfig, auto?: AutoContextMode): Promise<{ modelEnv: Record<string, string>; windows: Record<string, number> }> {
  const { boundedContextWindows, buildClaudeContextWindows, effectiveModelEnv } = await import("../claude/context-windows");
  const windows = await boundedContextWindows(async () => {
    const { gatherRoutedModels, nativeContextLimits, visibleNativeSlugs } = await import("../codex/catalog");
    try {
      return buildClaudeContextWindows([...visibleNativeSlugs(config)], await gatherRoutedModels(config), nativeContextLimits(config));
    } catch (error) {
      if (error && typeof error === "object" && (error as { code?: unknown }).code === "catalog_busy") {
        return buildClaudeContextWindows([...visibleNativeSlugs(config)], [], nativeContextLimits(config));
      }
      throw error;
    }
  });
  return { modelEnv: effectiveModelEnv(config.claudeCode, windows ?? {}, auto), windows: windows ?? {} };
}

export async function injectSystemEnv(
  port: number,
  config: OcxConfig,
  deps: SystemEnvDeps = {},
): Promise<SystemEnvResult> {
  if (process.platform !== "darwin") return { injected: false, reason: "not macOS" };
  if (config.claudeCode?.enabled === false) return { injected: false, reason: "claude disabled" };

  // Default OFF — only inject when explicitly enabled by the user.
  if (config.claudeCode?.systemEnv !== true) return { injected: false, reason: "systemEnv disabled" };

  await cleanStaleSystemEnv();

  const currentBaseUrl = launchctlGetenv("ANTHROPIC_BASE_URL");
  if (currentBaseUrl && !/^http:\/\/127\.0\.0\.1:\d+$/.test(currentBaseUrl)) {
    return { injected: false, reason: "user has custom ANTHROPIC_BASE_URL" };
  }
  // After stale cleanup, if a tracking file still exists with a DIFFERENT port,
  // another live instance owns the env — don't overwrite it.
  const existingTracking = readTracking();
  if (existingTracking && existingTracking.port !== port) {
    return { injected: false, reason: `another instance owns env (port ${existingTracking.port})` };
  }

  const injectedKeys: string[] = existingTracking
    ? [...(existingTracking.injectedKeys ?? SYSTEM_ENV_NAMES)]
    : [];
  const inject = (name: string, value: string) => {
    setLaunchctlEnv(name, value);
    if (!injectedKeys.includes(name)) injectedKeys.push(name);
    writeTracking(port, injectedKeys);
  };

  try {
    inject("ANTHROPIC_BASE_URL", ownedBaseUrl(port));
    inject("CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY", "1");
    const markerMode = systemEnvMarkerMode(config, deps);
    if (markerMode === "proxy") {
      if (config.apiKeys?.length) {
        inject("ANTHROPIC_AUTH_TOKEN", config.apiKeys[0].key);
      } else if (launchctlGetenv("ANTHROPIC_AUTH_TOKEN") === undefined) {
        inject("ANTHROPIC_AUTH_TOKEN", PROXY_MARKER);
      }
    } else if (injectedKeys.includes("ANTHROPIC_AUTH_TOKEN")) {
      const currentToken = launchctlGetenv("ANTHROPIC_AUTH_TOKEN");
      if (currentToken
        && (currentToken === PROXY_MARKER || isProxyAdmissionSecret(currentToken, config))) {
        // Subscription switch-back (devlog 260720_claude_authmode_persist): remove
        // opencodex-owned dummy or admission tokens so a launchd-started Claude regains
        // its own claude.ai OAuth. User-set tokens are never touched.
        unsetLaunchctlEnv("ANTHROPIC_AUTH_TOKEN");
        const tokenIdx = injectedKeys.indexOf("ANTHROPIC_AUTH_TOKEN");
        if (tokenIdx >= 0) injectedKeys.splice(tokenIdx, 1);
        writeTracking(port, injectedKeys);
      }
    }
    // Lever keys (devlog 136 B6): user-wins — skip any key the user already set in the
    // launchd domain, and track ONLY the keys we actually injected so revert cannot
    // delete a pre-existing user value (audit 139 #3).
    const injectLever = (name: string, value: string) => {
      if (launchctlGetenv(name) !== undefined) return;
      inject(name, value);
    };
    // Model slots (default + tier defaults + legacy small-fast) with [1m] auto-marking
    // (devlog 260712 B2, audit R2#3/R4#3): in-process context-window computation under
    // the same 3s bound; on timeout the tier keys are simply not injected this run.
    // Auto-context: a user-owned launchd value drives the marking predicate so the
    // marker and threshold never separate (audit 021 #2); injectLever's user-wins
    // check below keeps that value untouched.
    const userAutoCompact = launchctlGetenv("CLAUDE_CODE_AUTO_COMPACT_WINDOW");
    const auto = resolveAutoContext(config.claudeCode, userAutoCompact);
    const { modelEnv, windows } = await computeEffectiveModelEnv(config, auto);
    for (const [name, value] of Object.entries(modelEnv)) {
      if (name === "ANTHROPIC_MODEL") continue; // legacy slot handled by shell file only (back-compat)
      injectLever(name, value);
    }
    const maxCtx = config.claudeCode?.maxContextTokens;
    if (typeof maxCtx === "number" && Number.isFinite(maxCtx) && maxCtx > 0) {
      injectLever("CLAUDE_CODE_MAX_CONTEXT_TOKENS", String(Math.floor(maxCtx)));
      injectLever("DISABLE_COMPACT", "1");
    }
    // Auto-context (devlog 260712 020): user-wins lever, inert when maxContextTokens set.
    if (auto.enabled) injectLever("CLAUDE_CODE_AUTO_COMPACT_WINDOW", String(auto.compactWindow));
    if (config.claudeCode?.alwaysEnableEffort === true) {
      injectLever("CLAUDE_CODE_ALWAYS_ENABLE_EFFORT", "1");
    }

    // Shell-hook env file: works for new shells in already-running Terminal.app.
    writeShellEnvFile(port, config, modelEnv, auto, deps);

    // Gateway-model cache pre-write (devlog 030): plain `claude` sessions read the
    // picker list from ~/.claude/cache/gateway-models.json and cannot refresh it
    // without a token — keep it in sync with this proxy's /v1/models. Best-effort.
    try {
      const { refreshGatewayModelCacheFromProxy } = await import("../claude/gateway-cache");
      await refreshGatewayModelCacheFromProxy(port, { admissionConfig: config });
    } catch { /* best-effort */ }

    // Roster agent definitions (devlog 070): same launch-time sync for plain `claude`.
    // Reuses the window map computed above (audit 071 #5 — no second acquisition).
    try {
      const { injectClaudeAgentDefs } = await import("../claude/agents-inject");
      injectClaudeAgentDefs(config, windows);
    } catch { /* best-effort */ }

    writeTracking(port, injectedKeys);
  } catch (error) {
    rollbackInjectedKeys(port, injectedKeys);
    removeShellEnvFile();
    console.error("Failed to inject system environment; rolled back launchctl changes:", error);
    throw error;
  }

  return { injected: true };
}

export async function applySystemEnvToggle(config: OcxConfig, port: number): Promise<SystemEnvResult | RevertResult> {
  if (config.claudeCode?.systemEnv === true) return injectSystemEnv(port, config);
  return revertSystemEnv();
}

export function revertSystemEnv(): RevertResult {
  if (process.platform !== "darwin") return { reverted: false, reason: "not macOS" };

  const tracking = readTracking();
  if (!tracking) return { reverted: false, reason: "no tracking file" };

  try {
    const tracksBaseUrl = tracking.injectedKeys?.includes("ANTHROPIC_BASE_URL") ?? true;
    if (tracksBaseUrl && launchctlGetenv("ANTHROPIC_BASE_URL") !== ownedBaseUrl(tracking.port)) {
      return { reverted: false, reason: "ownership mismatch" };
    }

    // Only unset keys that were actually injected (preserves pre-existing user tokens).
    const keysToUnset = tracking.injectedKeys ?? SYSTEM_ENV_NAMES as unknown as string[];
    for (const name of keysToUnset) {
      try {
        unsetLaunchctlEnv(name);
      } catch {
        // Continue removing the remaining variables during shutdown.
      }
    }
    removeShellEnvFile();
    try {
      unlinkSync(getSystemEnvTrackingPath());
    } catch {
      // The environment was reverted even if the tracking file disappeared concurrently.
    }
    return { reverted: true };
  } catch {
    return { reverted: false, reason: "revert failed" };
  }
}

export async function cleanStaleSystemEnv(): Promise<CleanupResult> {
  const tracking = readTracking();
  if (!tracking) return { cleaned: false, reason: "no tracking file" };

  try {
    const response = await fetch(`${ownedBaseUrl(tracking.port)}/healthz`, {
      signal: AbortSignal.timeout(1_000),
    });
    if (response.ok) return { cleaned: false, reason: "proxy still alive" };
  } catch {
    // A failed or timed-out health check means the tracked proxy is stale.
  }

  const reverted = revertSystemEnv();
  if (!reverted.reverted) return { cleaned: false, reason: reverted.reason };
  return { cleaned: true };
}
