export interface StatusCodeInfo { label: string; description: string }

type Locale = "en" | "de" | "fr" | "ko" | "zh" | "zh-TW" | "ru" | "ja" | "tr" | "vi";
type LocalizedInfo = Record<Locale, StatusCodeInfo>;

const STATUS_CODES: Record<number, LocalizedInfo> = {
  400: {
    en: { label: "Bad request", description: "The proxy could not understand the request. Check the model, message shape, headers, and JSON body before retrying." },
    fr: { label: "Requête incorrecte", description: "Le proxy n’a pas pu comprendre la requête. Vérifiez le modèle, la structure des messages, les en-têtes et le corps JSON avant de réessayer." },
    ko: { label: "잘못된 요청", description: "프록시가 요청을 이해할 수 없습니다. 재시도 전에 모델, 메시지 형식, 헤더, JSON 본문을 확인해야 합니다." },
    zh: { label: "错误请求", description: "代理无法理解该请求。重试前请检查模型、消息结构、标头和 JSON 正文。" },
    "zh-TW": { label: "錯誤請求", description: "代理無法理解該請求。重試前請檢查模型、訊息結構、標頭和 JSON 本文。" },
    de: { label: "Ungültige Anfrage", description: "Der Proxy konnte die Anfrage nicht verstehen. Prüfe Modell, Nachrichtenformat, Header und JSON-Body vor einem erneuten Versuch." },
    ru: { label: "Некорректный запрос", description: "Прокси не смог интерпретировать запрос. Перед повторной попыткой проверьте модель, формат сообщений, заголовки и тело JSON." },
    ja: { label: "不正なリクエスト", description: "プロキシがリクエストを解釈できませんでした。再試行前にモデル、メッセージ形式、ヘッダー、JSON 本文を確認してください。" },
    tr: { label: "Hatalı istek", description: "Proxy isteği anlayamadı. Yeniden denemeden önce modeli, mesaj yapısını, başlıkları ve JSON gövdesini kontrol edin." },
    vi: { label: "Yêu cầu không hợp lệ", description: "Proxy không thể hiểu yêu cầu. Hãy kiểm tra model, cấu trúc tin nhắn, header và nội dung JSON trước khi thử lại." },
  },
  401: {
    en: { label: "Unauthorized", description: "Credentials are missing, expired, or invalid. Re-login or refresh the account/provider credentials used by opencodex." },
    fr: { label: "Non autorisé", description: "Les identifiants sont absents, expirés ou non valides. Reconnectez-vous ou actualisez les identifiants du compte ou du fournisseur utilisés par opencodex." },
    ko: { label: "인증 필요", description: "자격 증명이 없거나 만료되었거나 유효하지 않습니다. opencodex에서 사용하는 계정 또는 제공자 자격 증명을 다시 로그인하거나 갱신해야 합니다." },
    zh: { label: "未授权", description: "凭据缺失、已过期或无效。请重新登录，或刷新 opencodex 使用的账号/提供商凭据。" },
    "zh-TW": { label: "未授權", description: "憑證缺失、已過期或無效。請重新登入，或重新整理 opencodex 使用的帳號/供應商憑證。" },
    de: { label: "Nicht autorisiert", description: "Anmeldedaten fehlen, sind abgelaufen oder ungültig. Melde dich erneut an oder aktualisiere die von opencodex genutzten Konto-/Anbieter-Zugangsdaten." },
    ru: { label: "Не авторизован", description: "Учётные данные отсутствуют, истекли или недействительны. Войдите заново или обновите учётные данные аккаунта или провайдера, которые использует opencodex." },
    ja: { label: "認証が必要", description: "認証情報が不在・期限切れ・無効です。opencodex が使用するアカウントまたはプロバイダー認証情報を再ログインまたは更新してください。" },
    tr: { label: "Yetkisiz erişim", description: "Kimlik bilgileri eksik, süresi dolmuş veya geçersiz. opencodex tarafından kullanılan hesap veya sağlayıcı kimlik bilgilerini yeniden doğrulayın." },
    vi: { label: "Chưa xác thực", description: "Thông tin xác thực bị thiếu, đã hết hạn hoặc không hợp lệ. Hãy đăng nhập lại hoặc làm mới thông tin xác thực của tài khoản hay nhà cung cấp mà opencodex sử dụng." },
  },
  402: {
    en: { label: "Payment required", description: "The upstream provider rejected the request because billing, credits, or plan access is not available. Add credits, update billing, or switch provider." },
    fr: { label: "Paiement requis", description: "Le fournisseur en amont a rejeté la requête, car la facturation, les crédits ou l’accès à l’offre ne sont pas disponibles. Ajoutez des crédits, mettez à jour la facturation ou changez de fournisseur." },
    ko: { label: "결제 필요", description: "청구, 크레딧, 플랜 접근 권한 문제로 업스트림 제공자가 요청을 거부했습니다. 크레딧 추가, 결제 정보 갱신, 제공자 전환이 필요합니다." },
    zh: { label: "需要付款", description: "上游提供商因账单、额度或套餐权限不可用而拒绝了请求。请充值、更新账单信息或切换提供商。" },
    "zh-TW": { label: "需要付款", description: "上游供應商因帳單、額度或方案許可權不可用而拒絕了請求。請儲值、更新帳單資訊或切換供應商。" },
    de: { label: "Zahlung erforderlich", description: "Der Upstream-Anbieter hat die Anfrage abgelehnt, weil Abrechnung, Guthaben oder Planzugriff nicht verfügbar ist. Guthaben aufladen, Abrechnung aktualisieren oder Anbieter wechseln." },
    ru: { label: "Требуется оплата", description: "Вышестоящий провайдер отклонил запрос из-за проблем с оплатой, кредитами или доступом по тарифному плану. Пополните баланс, обновите платёжные данные или переключитесь на другого провайдера." },
    ja: { label: "支払いが必要", description: "課金、クレジット、プランアクセスが利用できないため上流プロバイダーがリクエストを拒否しました。クレジット追加、支払い情報更新、プロバイダー切替が必要です。" },
    tr: { label: "Ödeme gerekli", description: "Yukarı akış sağlayıcısı faturalandırma, kredi veya plan erişimi bulunmadığından isteği reddetti. Kredi ekleyin, ödeme bilgilerini güncelleyin veya sağlayıcı değiştirin." },
    vi: { label: "Yêu cầu thanh toán", description: "Nhà cung cấp upstream đã từ chối yêu cầu vì không có quyền truy cập thanh toán, tín dụng hoặc gói dịch vụ. Hãy thêm tín dụng, cập nhật thanh toán hoặc đổi nhà cung cấp." },
  },
  403: {
    en: { label: "Forbidden", description: "The account is authenticated but not allowed to use this model or operation. Often a plan/subscription gate (e.g. Ollama Cloud Pro), org policy, or model permission — not necessarily a bad API key." },
    fr: { label: "Accès interdit", description: "Le compte est authentifié, mais n’est pas autorisé à utiliser ce modèle ou cette opération. Il s’agit souvent d’une restriction liée à l’offre ou à l’abonnement (p. ex. Ollama Cloud Pro), à la politique de l’organisation ou aux autorisations du modèle — pas nécessairement d’une clé API incorrecte." },
    ko: { label: "권한 없음", description: "계정 인증은 되었지만 이 모델 또는 작업을 사용할 권한이 없습니다. 플랜/구독 제한(예: Ollama Cloud Pro), 조직 정책, 모델 권한 문제인 경우가 많으며 API 키가 잘못된 것은 아닐 수 있습니다." },
    zh: { label: "禁止访问", description: "账号已认证，但无权使用此模型或操作。常见原因是套餐/订阅限制（例如 Ollama Cloud Pro）、组织策略或模型权限——不一定是 API 密钥无效。" },
    "zh-TW": { label: "禁止存取", description: "帳號已認證，但無權使用此模型或操作。常見原因是方案/訂閱限制（例如 Ollama Cloud Pro）、組織策略或模型許可權——不一定是 API 金鑰無效。" },
    de: { label: "Verboten", description: "Das Konto ist authentifiziert, darf dieses Modell oder diese Operation aber nicht nutzen. Oft Plan-/Abo-Sperre (z. B. Ollama Cloud Pro), Organisationsrichtlinie oder Modellrecht — nicht zwingend ein ungültiger API-Key." },
    ru: { label: "Доступ запрещён", description: "Аккаунт аутентифицирован, но не имеет права использовать эту модель или операцию. Часто причина — ограничение тарифа или подписки (например, Ollama Cloud Pro), политика организации или права доступа к модели, а не обязательно неверный API-ключ." },
    ja: { label: "アクセス禁止", description: "アカウントは認証済みですがこのモデルや操作の使用が許可されていません。多くはプラン/サブスクリプション制限（例: Ollama Cloud Pro）、組織ポリシー、モデル権限であり、API キーが不正とは限りません。" },
    tr: { label: "Erişim yasaklandı", description: "Hesabın kimliği doğrulandı ancak bu modeli veya işlemi kullanma izni yok. Genellikle plan/abonelik sınırı (örn. Ollama Cloud Pro), organizasyon politikası veya model izni kaynaklıdır." },
    vi: { label: "Bị cấm", description: "Tài khoản đã được xác thực nhưng không được phép dùng model hoặc thao tác này. Nguyên nhân thường là giới hạn gói hoặc thuê bao (ví dụ Ollama Cloud Pro), chính sách tổ chức hay quyền model — không nhất thiết do API key sai." },
  },
  404: {
    en: { label: "Not found", description: "The requested route, model, account, or upstream resource was not found. Verify the model name and opencodex provider configuration." },
    fr: { label: "Introuvable", description: "La route, le modèle, le compte ou la ressource en amont demandés sont introuvables. Vérifiez le nom du modèle et la configuration du fournisseur opencodex." },
    ko: { label: "찾을 수 없음", description: "요청한 경로, 모델, 계정 또는 업스트림 리소스를 찾을 수 없습니다. 모델 이름과 opencodex 제공자 설정을 확인해야 합니다." },
    zh: { label: "未找到", description: "找不到请求的路由、模型、账号或上游资源。请确认模型名称和 opencodex 提供商配置。" },
    "zh-TW": { label: "未找到", description: "找不到請求的路由、模型、帳號或上游資源。請確認模型名稱和 opencodex 供應商配置。" },
    de: { label: "Nicht gefunden", description: "Die angeforderte Route, das Modell, das Konto oder die Upstream-Ressource wurde nicht gefunden. Prüfe Modellname und opencodex-Anbieterkonfiguration." },
    ru: { label: "Не найдено", description: "Запрошенный маршрут, модель, аккаунт или вышестоящий ресурс не найден. Проверьте имя модели и конфигурацию провайдера в opencodex." },
    ja: { label: "見つかりません", description: "要求されたルート、モデル、アカウント、上流リソースが見つかりませんでした。モデル名と opencodex プロバイダー設定を確認してください。" },
    tr: { label: "Bulunamadı", description: "İstenen rota, model, hesap veya yukarı akış kaynağı bulunamadı. Model adını ve opencodex sağlayıcı yapılandırmasını doğrulayın." },
    vi: { label: "Không tìm thấy", description: "Không tìm thấy endpoint, model hoặc tài nguyên được yêu cầu. Hãy kiểm tra base URL, tên model và đường dẫn yêu cầu." },
  },
  408: {
    en: { label: "Request timeout", description: "The request took too long before the proxy or upstream provider could complete it. Retry with a smaller request or a different provider." },
    fr: { label: "Délai d’attente de la requête dépassé", description: "La requête a pris trop de temps pour que le proxy ou le fournisseur en amont puisse la traiter. Réessayez avec une requête plus petite ou un autre fournisseur." },
    ko: { label: "요청 시간 초과", description: "프록시 또는 업스트림 제공자가 요청을 완료하기 전에 시간이 초과되었습니다. 더 작은 요청으로 재시도하거나 다른 제공자로 전환해야 합니다." },
    zh: { label: "请求超时", description: "代理或上游提供商未能在限定时间内完成请求。请缩小请求后重试，或切换提供商。" },
    "zh-TW": { label: "請求逾時", description: "代理或上游供應商未能在限定時間內完成請求。請縮小請求後重試，或切換供應商。" },
    de: { label: "Anfrage-Timeout", description: "Die Anfrage dauerte zu lange, bevor Proxy oder Upstream-Anbieter sie abschließen konnten. Mit kleinerer Anfrage oder anderem Anbieter erneut versuchen." },
    ru: { label: "Тайм-аут запроса", description: "Обработка запроса заняла слишком много времени, и прокси или вышестоящий провайдер не успел её завершить. Повторите попытку с меньшим запросом или через другого провайдера." },
    ja: { label: "リクエストタイムアウト", description: "プロキシまたは上流プロバイダーがリクエストを完了する前に時間切れになりました。より小さいリクエストで再試行するか、別のプロバイダーに切り替えてください。" },
    tr: { label: "İstek zaman aşımı", description: "Proxy veya yukarı akış sağlayıcısı isteği tamamlayamadan zaman aşımına uğradı. Daha küçük bir istek veya farklı bir sağlayıcı ile tekrar deneyin." },
    vi: { label: "Yêu cầu hết thời gian chờ", description: "Yêu cầu không hoàn tất trước thời hạn. Hãy thử lại với yêu cầu nhỏ hơn hoặc kiểm tra kết nối mạng." },
  },
  409: {
    en: { label: "Conflict", description: "The request conflicts with the current account, session, or provider state. Refresh the session or retry after the active operation finishes." },
    fr: { label: "Conflit", description: "La requête entre en conflit avec l’état actuel du compte, de la session ou du fournisseur. Actualisez la session ou réessayez une fois l’opération en cours terminée." },
    ko: { label: "상태 충돌", description: "요청이 현재 계정, 세션 또는 제공자 상태와 충돌합니다. 세션을 갱신하거나 진행 중인 작업이 끝난 뒤 재시도해야 합니다." },
    zh: { label: "状态冲突", description: "请求与当前账号、会话或提供商状态冲突。请刷新会话，或等待当前操作完成后重试。" },
    "zh-TW": { label: "狀態衝突", description: "請求與當前帳號、會話或供應商狀態衝突。請重新整理會話，或等待當前操作完成後重試。" },
    de: { label: "Konflikt", description: "Die Anfrage kollidiert mit dem aktuellen Konto-, Sitzungs- oder Anbieterstatus. Sitzung aktualisieren oder nach Abschluss der laufenden Operation erneut versuchen." },
    ru: { label: "Конфликт", description: "Запрос конфликтует с текущим состоянием аккаунта, сессии или провайдера. Обновите сессию или повторите попытку после завершения текущей операции." },
    ja: { label: "状態の衝突", description: "リクエストが現在のアカウント、セッション、プロバイダー状態と衝突しています。セッションを更新するか、進行中の操作が終わった後に再試行してください。" },
    tr: { label: "Durum çakışması", description: "İstek mevcut hesap, oturum veya sağlayıcı durumuyla çakışıyor. Oturumu yenileyin veya aktif işlem bittikten sonra tekrar deneyin." },
    vi: { label: "Xung đột", description: "Yêu cầu xung đột với trạng thái hiện tại của tài nguyên hoặc tài khoản. Hãy làm mới trạng thái rồi thử lại." },
  },
  413: {
    en: { label: "Request too large", description: "The prompt, attachments, or generated payload exceeds a proxy or upstream limit. Reduce tokens, file size, or conversation history." },
    fr: { label: "Requête trop volumineuse", description: "L’invite, les pièces jointes ou la charge utile générée dépassent une limite du proxy ou du fournisseur en amont. Réduisez le nombre de jetons, la taille des fichiers ou l’historique de la conversation." },
    ko: { label: "요청 과대", description: "프롬프트, 첨부 파일 또는 생성 페이로드가 프록시나 업스트림 한도를 초과했습니다. 토큰, 파일 크기, 대화 기록을 줄여야 합니다." },
    zh: { label: "请求过大", description: "提示、附件或生成的负载超过了代理或上游限制。请减少 token、文件大小或对话历史。" },
    "zh-TW": { label: "請求過大", description: "提示、附件或生成的負載超過了代理或上游限制。請減少 token、檔案大小或對話歷史。" },
    de: { label: "Anfrage zu groß", description: "Prompt, Anhänge oder generierte Nutzlast überschreiten ein Proxy- oder Upstream-Limit. Tokens, Dateigröße oder Verlauf reduzieren." },
    ru: { label: "Слишком большой запрос", description: "Промпт, вложения или сформированная полезная нагрузка превышают лимит прокси или вышестоящего провайдера. Сократите количество токенов, размер файлов или историю диалога." },
    ja: { label: "リクエストが大きすぎます", description: "プロンプト、添付ファイル、生成ペイロードがプロキシまたは上流の制限を超えました。トークン、ファイルサイズ、会話履歴を減らしてください。" },
    tr: { label: "İstek çok büyük", description: "İstemi, ekler veya oluşturulan veri proxy ya da yukarı akış sınırını aşıyor. Jeton sayısını, dosya boyutunu veya sohbet geçmişini azaltın." },
    vi: { label: "Nội dung quá lớn", description: "Nội dung yêu cầu vượt quá giới hạn của proxy hoặc nhà cung cấp. Hãy giảm kích thước tin nhắn, tệp hoặc ngữ cảnh rồi thử lại." },
  },
  422: {
    en: { label: "Invalid content", description: "The provider accepted the request format but rejected its contents. Check model options, tool definitions, message roles, and unsupported fields." },
    fr: { label: "Contenu non valide", description: "Le fournisseur a accepté le format de la requête, mais en a rejeté le contenu. Vérifiez les options du modèle, les définitions des outils, les rôles des messages et les champs non pris en charge." },
    ko: { label: "내용 검증 실패", description: "제공자가 요청 형식은 받았지만 내용을 거부했습니다. 모델 옵션, 도구 정의, 메시지 역할, 지원되지 않는 필드를 확인해야 합니다." },
    zh: { label: "内容无效", description: "提供商接受了请求格式，但拒绝了其中的内容。请检查模型选项、工具定义、消息角色和不支持的字段。" },
    "zh-TW": { label: "內容無效", description: "供應商接受了請求格式，但拒絕了其中的內容。請檢查模型選項、工具定義、訊息角色和不支援的欄位。" },
    de: { label: "Ungültiger Inhalt", description: "Der Anbieter akzeptierte das Anfrageformat, lehnte den Inhalt aber ab. Prüfe Modelloptionen, Tool-Definitionen, Nachrichtenrollen und nicht unterstützte Felder." },
    ru: { label: "Недопустимое содержимое", description: "Провайдер принял формат запроса, но отклонил его содержимое. Проверьте параметры модели, определения инструментов, роли сообщений и неподдерживаемые поля." },
    ja: { label: "内容の検証失敗", description: "プロバイダーはリクエスト形式を受け付けましたが内容を拒否しました。モデルオプション、ツール定義、メッセージロール、未サポートのフィールドを確認してください。" },
    tr: { label: "Geçersiz içerik", description: "Sağlayıcı istek formatını kabul etti ancak içeriğini reddetti. Model seçeneklerini, araç tanımlarını, mesaj rollerini ve desteklenmeyen alanları kontrol edin." },
    vi: { label: "Yêu cầu không thể xử lý", description: "Yêu cầu có cú pháp hợp lệ nhưng chứa giá trị hoặc tổ hợp tùy chọn mà model hay nhà cung cấp không hỗ trợ." },
  },
  424: {
    en: { label: "Provider dependency failed", description: "A required upstream dependency failed while opencodex was routing the request. Retry later or switch to another configured provider." },
    fr: { label: "Échec d’une dépendance du fournisseur", description: "Une dépendance en amont requise a échoué pendant le routage de la requête par opencodex. Réessayez plus tard ou sélectionnez un autre fournisseur configuré." },
    ko: { label: "제공자 의존성 실패", description: "opencodex가 요청을 라우팅하는 동안 필요한 업스트림 의존성이 실패했습니다. 나중에 재시도하거나 다른 설정된 제공자로 전환해야 합니다." },
    zh: { label: "提供商依赖失败", description: "opencodex 路由请求时，必需的上游依赖失败。请稍后重试，或切换到另一个已配置的提供商。" },
    "zh-TW": { label: "供應商依賴失敗", description: "opencodex 路由請求時，必需的上游依賴失敗。請稍後重試，或切換到另一個已配置的供應商。" },
    de: { label: "Anbieter-Abhängigkeit fehlgeschlagen", description: "Eine erforderliche Upstream-Abhängigkeit ist fehlgeschlagen, während opencodex die Anfrage geroutet hat. Später erneut versuchen oder zu einem anderen Anbieter wechseln." },
    ru: { label: "Сбой зависимости провайдера", description: "Необходимая вышестоящая зависимость дала сбой, пока opencodex маршрутизировал запрос. Повторите попытку позже или переключитесь на другого настроенного провайдера." },
    ja: { label: "プロバイダー依存の失敗", description: "opencodex がリクエストをルーティング中に必要な上流依存が失敗しました。後で再試行するか、別の設定済みプロバイダーに切り替えてください。" },
    tr: { label: "Sağlayıcı bağımlılığı başarısız", description: "opencodex isteği yönlendirirken gerekli bir yukarı akış bağımlılığı başarısız oldu. Daha sonra tekrar deneyin veya başka bir sağlayıcıya geçin." },
    vi: { label: "Phụ thuộc thất bại", description: "Không thể hoàn tất yêu cầu vì một dịch vụ phụ thuộc hoặc thao tác upstream đã thất bại. Hãy kiểm tra lỗi liên quan rồi thử lại." },
  },
  429: {
    en: { label: "Rate limited", description: "The upstream provider rate or quota limit has been reached. Wait for the quota window to reset or switch account/provider." },
    fr: { label: "Limite de débit atteinte", description: "La limite de débit ou de quota du fournisseur en amont a été atteinte. Attendez la réinitialisation de la fenêtre de quota ou changez de compte ou de fournisseur." },
    ko: { label: "한도 초과", description: "업스트림 제공자의 속도 또는 할당량 한도에 도달했습니다. 한도 창이 초기화될 때까지 기다리거나 계정/제공자를 전환해야 합니다." },
    zh: { label: "限流", description: "已达到上游提供商的速率或额度限制。请等待额度窗口重置，或切换账号/提供商。" },
    "zh-TW": { label: "限流", description: "已達到上游供應商的速率或額度限制。請等待額度視窗重設，或切換帳號/供應商。" },
    de: { label: "Ratenlimit erreicht", description: "Das Raten- oder Kontingentlimit des Upstream-Anbieters ist erreicht. Auf Reset des Kontingentfensters warten oder Konto/Anbieter wechseln." },
    ru: { label: "Превышен лимит запросов", description: "Достигнут лимит скорости или квота вышестоящего провайдера. Дождитесь сброса окна квоты или переключитесь на другой аккаунт или провайдера." },
    ja: { label: "レート制限", description: "上流プロバイダーのレートまたはクォータ制限に達しました。クォータウィンドウがリセットされるまで待つか、アカウント/プロバイダーを切り替えてください。" },
    tr: { label: "Oran sınırı aşıldı", description: "Yukarı akış sağlayıcısının hız veya kota sınırına ulaşıldı. Kota penceresinin sıfırlanmasını bekleyin ya da hesap/sağlayıcı değiştirin." },
    vi: { label: "Quá nhiều yêu cầu", description: "Tài khoản hoặc nhà cung cấp đã đạt giới hạn tốc độ hay hạn ngạch. Hãy chờ thời gian Retry-After, đổi tài khoản hoặc đổi nhà cung cấp." },
  },
  499: {
    en: { label: "Client closed request", description: "The client disconnected or canceled the request before opencodex finished routing it. Retry if the cancellation was accidental." },
    fr: { label: "Requête fermée par le client", description: "Le client s’est déconnecté ou a annulé la requête avant la fin de son routage par opencodex. Réessayez si l’annulation était involontaire." },
    ko: { label: "클라이언트 취소", description: "opencodex가 라우팅을 끝내기 전에 클라이언트 연결이 끊기거나 요청이 취소되었습니다. 의도한 취소가 아니면 다시 시도해야 합니다." },
    zh: { label: "客户端已取消", description: "opencodex 完成路由前，客户端已断开连接或取消请求。如果不是有意取消，请重试。" },
    "zh-TW": { label: "客戶端已取消", description: "opencodex 完成路由前，客戶端已斷開連線或取消請求。如果不是有意取消，請重試。" },
    de: { label: "Client hat Anfrage geschlossen", description: "Der Client hat die Verbindung getrennt oder die Anfrage abgebrochen, bevor opencodex das Routing abgeschlossen hat. Bei versehentlichem Abbruch erneut versuchen." },
    ru: { label: "Запрос закрыт клиентом", description: "Клиент отключился или отменил запрос до того, как opencodex завершил его маршрутизацию. Если отмена была случайной, повторите попытку." },
    ja: { label: "クライアントがリクエストをクローズ", description: "opencodex がルーティングを終える前にクライアントが切断またはキャンセルしました。意図しないキャンセルなら再試行してください。" },
    tr: { label: "İstemci isteği kapattı", description: "opencodex yönlendirmeyi bitirmeden önce istemci bağlantıyı kesti veya isteği iptal etti. İptal kazara yapıldıysa tekrar deneyin." },
    vi: { label: "Máy khách đã đóng yêu cầu", description: "Máy khách đã ngắt kết nối hoặc hủy yêu cầu trước khi opencodex định tuyến xong. Nếu không chủ ý hủy, hãy thử lại." },
  },
  500: {
    en: { label: "Proxy error", description: "opencodex hit an internal error while handling the request. Retry once, then check proxy logs if it repeats." },
    fr: { label: "Erreur du proxy", description: "opencodex a rencontré une erreur interne lors du traitement de la requête. Réessayez une fois, puis consultez les journaux du proxy si l’erreur se reproduit." },
    ko: { label: "프록시 오류", description: "opencodex가 요청을 처리하는 동안 내부 오류가 발생했습니다. 한 번 재시도하고 반복되면 프록시 로그를 확인해야 합니다." },
    zh: { label: "代理错误", description: "opencodex 处理请求时发生内部错误。请先重试一次；如果重复出现，请检查代理日志。" },
    "zh-TW": { label: "代理錯誤", description: "opencodex 處理請求時發生內部錯誤。請先重試一次；如果重複出現，請檢查代理日誌。" },
    de: { label: "Proxy-Fehler", description: "opencodex ist bei der Anfragebearbeitung auf einen internen Fehler gestoßen. Einmal erneut versuchen, bei Wiederholung Proxy-Logs prüfen." },
    ru: { label: "Ошибка прокси", description: "В opencodex произошла внутренняя ошибка при обработке запроса. Повторите попытку один раз; если ошибка повторяется, проверьте логи прокси." },
    ja: { label: "プロキシエラー", description: "opencodex がリクエスト処理中に内部エラーに遭遇しました。1 回再試行し、繰り返す場合はプロキシログを確認してください。" },
    tr: { label: "Proxy hatası", description: "opencodex isteği işlerken dahili bir hatayla karşılaştı. Bir kez tekrar deneyin, tekrarlarsa proxy günlüklerini kontrol edin." },
    vi: { label: "Lỗi proxy", description: "opencodex gặp lỗi nội bộ khi xử lý yêu cầu. Hãy thử lại một lần, rồi kiểm tra log proxy nếu lỗi lặp lại." },
  },
  502: {
    en: { label: "Bad upstream response", description: "The upstream provider returned an invalid or failed response through the proxy. Retry or route the request to another provider." },
    fr: { label: "Réponse incorrecte du fournisseur en amont", description: "Le fournisseur en amont a renvoyé une réponse non valide ou en échec par l’intermédiaire du proxy. Réessayez ou acheminez la requête vers un autre fournisseur." },
    ko: { label: "업스트림 응답 오류", description: "업스트림 제공자가 프록시를 통해 유효하지 않거나 실패한 응답을 반환했습니다. 재시도하거나 다른 제공자로 라우팅해야 합니다." },
    zh: { label: "上游响应错误", description: "上游提供商通过代理返回了无效或失败的响应。请重试，或将请求路由到其他提供商。" },
    "zh-TW": { label: "上游回應錯誤", description: "上游供應商透過代理返回了無效或失敗的回應。請重試，或將請求路由到其他供應商。" },
    de: { label: "Ungültige Upstream-Antwort", description: "Der Upstream-Anbieter lieferte über den Proxy eine ungültige oder fehlgeschlagene Antwort. Erneut versuchen oder zu einem anderen Anbieter routen." },
    ru: { label: "Некорректный ответ провайдера", description: "Вышестоящий провайдер вернул через прокси недействительный или ошибочный ответ. Повторите попытку или направьте запрос другому провайдеру." },
    ja: { label: "上流レスポンス不良", description: "上流プロバイダーがプロキシ経由で無効または失敗したレスポンスを返しました。再試行するか、リクエストを別のプロバイダーにルーティングしてください。" },
    tr: { label: "Kötü yukarı akış yanıtı", description: "Yukarı akış sağlayıcısı proxy üzerinden geçersiz veya başarısız bir yanıt döndürdü. Tekrar deneyin veya isteği başka bir sağlayıcıya yönlendirin." },
    vi: { label: "Phản hồi upstream không hợp lệ", description: "Nhà cung cấp upstream trả về phản hồi không hợp lệ hoặc thất bại qua proxy. Hãy thử lại hoặc định tuyến yêu cầu sang nhà cung cấp khác." },
  },
  503: {
    en: { label: "Provider unavailable", description: "The proxy or upstream provider is temporarily unavailable or overloaded. Wait briefly, then retry or switch provider." },
    fr: { label: "Fournisseur indisponible", description: "Le proxy ou le fournisseur en amont est temporairement indisponible ou surchargé. Patientez un instant, puis réessayez ou changez de fournisseur." },
    ko: { label: "제공자 사용 불가", description: "프록시 또는 업스트림 제공자가 일시적으로 사용할 수 없거나 과부하 상태입니다. 잠시 기다린 뒤 재시도하거나 제공자를 전환해야 합니다." },
    zh: { label: "提供商不可用", description: "代理或上游提供商暂时不可用或过载。请稍后重试，或切换提供商。" },
    "zh-TW": { label: "供應商不可用", description: "代理或上游供應商暫時不可用或過載。請稍後重試，或切換供應商。" },
    de: { label: "Anbieter nicht verfügbar", description: "Proxy oder Upstream-Anbieter ist vorübergehend nicht verfügbar oder überlastet. Kurz warten, dann erneut versuchen oder Anbieter wechseln." },
    ru: { label: "Провайдер недоступен", description: "Прокси или вышестоящий провайдер временно недоступен или перегружен. Немного подождите, затем повторите попытку или смените провайдера." },
    ja: { label: "プロバイダー利用不可", description: "プロキシまたは上流プロバイダーが一時的に利用不可または過負荷です。少し待ってから再試行するか、プロバイダーを切り替えてください。" },
    tr: { label: "Sağlayıcı kullanılamıyor", description: "Proxy veya yukarı akış sağlayıcısı geçici olarak kullanılamıyor veya aşırı yüklü. Kısa bir süre bekleyip tekrar deneyin ya da sağlayıcı değiştirin." },
    vi: { label: "Nhà cung cấp không khả dụng", description: "Proxy hoặc nhà cung cấp upstream tạm thời không khả dụng hay đang quá tải. Hãy chờ một lát rồi thử lại hoặc đổi nhà cung cấp." },
  },
  504: {
    en: { label: "Upstream timeout", description: "The upstream provider did not respond before the proxy timeout. Retry with a smaller request or choose a faster provider." },
    fr: { label: "Délai d’attente du fournisseur en amont dépassé", description: "Le fournisseur en amont n’a pas répondu avant l’expiration du délai du proxy. Réessayez avec une requête plus petite ou choisissez un fournisseur plus rapide." },
    ko: { label: "업스트림 시간 초과", description: "프록시 시간 제한 전에 업스트림 제공자가 응답하지 않았습니다. 더 작은 요청으로 재시도하거나 더 빠른 제공자를 선택해야 합니다." },
    zh: { label: "上游超时", description: "上游提供商未在代理超时前响应。请缩小请求后重试，或选择响应更快的提供商。" },
    "zh-TW": { label: "上游逾時", description: "上游供應商未在代理逾時前回應。請縮小請求後重試，或選擇回應更快的供應商。" },
    de: { label: "Upstream-Timeout", description: "Der Upstream-Anbieter antwortete nicht vor dem Proxy-Timeout. Mit kleinerer Anfrage erneut versuchen oder schnelleren Anbieter wählen." },
    ru: { label: "Тайм-аут вышестоящего провайдера", description: "Вышестоящий провайдер не ответил до истечения тайм-аута прокси. Повторите попытку с меньшим запросом или выберите более быстрого провайдера." },
    ja: { label: "上流タイムアウト", description: "上流プロバイダーがプロキシタイムアウト前に応答しませんでした。より小さいリクエストで再試行するか、より速いプロバイダーを選んでください。" },
    tr: { label: "Yukarı akış zaman aşımı", description: "Yukarı akış sağlayıcısı proxy zaman aşımı süresinden önce yanıt vermedi. Daha küçük bir istekle tekrar deneyin veya daha hızlı bir sağlayıcı seçin." },
    vi: { label: "Upstream hết thời gian chờ", description: "Nhà cung cấp upstream không phản hồi trước thời hạn của proxy. Hãy thử lại với yêu cầu nhỏ hơn hoặc chọn nhà cung cấp nhanh hơn." },
  },
  529: {
    en: { label: "Provider overloaded", description: "The upstream provider is overloaded or capacity-limited. Wait and retry, or switch to another account/provider." },
    fr: { label: "Fournisseur surchargé", description: "Le fournisseur en amont est surchargé ou sa capacité est limitée. Patientez et réessayez, ou changez de compte ou de fournisseur." },
    ko: { label: "제공자 과부하", description: "업스트림 제공자가 과부하 상태이거나 처리 용량이 제한되었습니다. 기다렸다가 재시도하거나 다른 계정/제공자로 전환해야 합니다." },
    zh: { label: "提供商过载", description: "上游提供商过载或容量受限。请等待后重试，或切换到其他账号/提供商。" },
    "zh-TW": { label: "供應商過載", description: "上游供應商過載或容量受限。請等待後重試，或切換到其他帳號/供應商。" },
    de: { label: "Anbieter überlastet", description: "Der Upstream-Anbieter ist überlastet oder kapazitätsbegrenzt. Warten und erneut versuchen oder anderes Konto/Anbieter nutzen." },
    ru: { label: "Провайдер перегружен", description: "Вышестоящий провайдер перегружен или ограничен по мощности. Подождите и повторите попытку либо переключитесь на другой аккаунт или провайдера." },
    ja: { label: "プロバイダー過負荷", description: "上流プロバイダーが過負荷または容量制限されています。待ってから再試行するか、別のアカウント/プロバイダーに切り替えてください。" },
    tr: { label: "Sağlayıcı aşırı yüklü", description: "Yukarı akış sağlayıcısı aşırı yüklü veya kapasitesi sınırlı. Bekleyip tekrar deneyin veya başka bir hesap/sağlayıcıya geçin." },
    vi: { label: "Nhà cung cấp quá tải", description: "Nhà cung cấp upstream đang quá tải hoặc bị giới hạn công suất. Hãy chờ rồi thử lại, hoặc đổi sang tài khoản hay nhà cung cấp khác." },
  },
};

const GENERIC_STATUS: { client: LocalizedInfo; server: LocalizedInfo } = {
  client: {
    en: { label: "Request error", description: "The proxy or upstream provider rejected the request. Check the request shape, credentials, model name, and provider configuration." },
    fr: { label: "Erreur de requête", description: "Le proxy ou le fournisseur en amont a rejeté la requête. Vérifiez sa structure, les identifiants, le nom du modèle et la configuration du fournisseur." },
    ko: { label: "요청 오류", description: "프록시 또는 업스트림 제공자가 요청을 거부했습니다. 요청 형식, 자격 증명, 모델 이름, 제공자 설정을 확인해야 합니다." },
    zh: { label: "请求错误", description: "代理或上游提供商拒绝了该请求。请检查请求结构、凭据、模型名称和提供商配置。" },
    "zh-TW": { label: "請求錯誤", description: "代理或上游供應商拒絕了該請求。請檢查請求結構、憑證、模型名稱和供應商配置。" },
    de: { label: "Anfragefehler", description: "Der Proxy oder Upstream-Anbieter hat die Anfrage abgelehnt. Prüfe Anfrageformat, Anmeldedaten, Modellname und Anbieterkonfiguration." },
    ru: { label: "Ошибка запроса", description: "Прокси или вышестоящий провайдер отклонил запрос. Проверьте структуру запроса, учётные данные, имя модели и конфигурацию провайдера." },
    ja: { label: "リクエストエラー", description: "プロキシまたは上流プロバイダーがリクエストを拒否しました。リクエスト形式、認証情報、モデル名、プロバイダー設定を確認してください。" },
    tr: { label: "İstek hatası", description: "Proxy veya yukarı akış sağlayıcısı isteği reddetti. İstek yapısını, kimlik bilgilerini, model adını ve sağlayıcı yapılandırmasını kontrol edin." },
    vi: { label: "Lỗi yêu cầu", description: "Proxy hoặc nhà cung cấp upstream đã từ chối yêu cầu. Hãy kiểm tra cấu trúc yêu cầu, thông tin xác thực, tên model và cấu hình nhà cung cấp." },
  },
  server: {
    en: { label: "Server or upstream error", description: "opencodex or an upstream provider failed while processing the request. Retry later or route the request to another provider." },
    fr: { label: "Erreur du serveur ou du fournisseur en amont", description: "opencodex ou un fournisseur en amont a échoué lors du traitement de la requête. Réessayez plus tard ou acheminez la requête vers un autre fournisseur." },
    ko: { label: "서버 또는 업스트림 오류", description: "opencodex 또는 업스트림 제공자가 요청 처리 중 실패했습니다. 나중에 재시도하거나 다른 제공자로 라우팅해야 합니다." },
    zh: { label: "服务器或上游错误", description: "opencodex 或上游提供商处理请求时失败。请稍后重试，或将请求路由到其他提供商。" },
    "zh-TW": { label: "伺服器或上游錯誤", description: "opencodex 或上游供應商處理請求時失敗。請稍後重試，或將請求路由到其他供應商。" },
    de: { label: "Server- oder Upstream-Fehler", description: "opencodex oder ein Upstream-Anbieter ist bei der Anfragebearbeitung fehlgeschlagen. Später erneut versuchen oder zu einem anderen Anbieter routen." },
    ru: { label: "Ошибка сервера или провайдера", description: "opencodex или вышестоящий провайдер завершил обработку запроса с ошибкой. Повторите попытку позже или направьте запрос другому провайдеру." },
    ja: { label: "サーバーまたは上流エラー", description: "opencodex または上流プロバイダーがリクエスト処理中に失敗しました。後で再試行するか、リクエストを別のプロバイダーにルーティングしてください。" },
    tr: { label: "Sunucu veya yukarı akış hatası", description: "opencodex veya bir yukarı akış sağlayıcısı isteği işlerken başarısız oldu. Daha sonra tekrar deneyin veya isteği başka bir sağlayıcıya yönlendirin." },
    vi: { label: "Lỗi máy chủ hoặc upstream", description: "opencodex hoặc một nhà cung cấp upstream đã thất bại khi xử lý yêu cầu. Hãy thử lại sau hoặc định tuyến yêu cầu sang nhà cung cấp khác." },
  },
};

function normalizeLocale(locale: string): Locale {
  if (locale.toLowerCase().startsWith("fr")) return "fr";
  if (locale.toLowerCase().startsWith("vi")) return "vi";
  return locale === "de" || locale === "ko" || locale === "zh" || locale === "zh-TW" || locale === "ru" || locale === "ja" || locale === "tr" ? locale : "en";
}

export function statusCodeInfo(code: number, locale: string): StatusCodeInfo | null {
  if (code < 400) return null;
  const normalizedLocale = normalizeLocale(locale);
  const info = STATUS_CODES[Math.trunc(code)] ?? (code < 500 ? GENERIC_STATUS.client : GENERIC_STATUS.server);
  return info[normalizedLocale];
}
