import { describe, expect, test } from "bun:test";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  buildReleaseNotes,
  categoryForTitle,
  hasRenderedPullReference,
  isPrereleaseVersion,
  isReleaseMetadataCommit,
  parseAssociatedPulls,
  parseGitLog,
  selectReleaseBaseline,
  trailingLandingPr,
  type ReleaseCommit,
} from "../scripts/build-release-changelog";
import { removeTreeWithRetry } from "./helpers/remove-tree";

const sha = (char: string): string => char.repeat(40);

function commit(
  id: string,
  subject: string,
  pulls: ReleaseCommit["pulls"] = [],
): ReleaseCommit {
  return {
    sha: sha(id),
    subject,
    body: subject,
    pulls,
  };
}

const generatedBugFix = [
  "<!-- Release notes generated by GitHub -->",
  "",
  "## What's Changed",
  "### Bug Fixes",
  "* fix(api): preserve generated PR coverage by @alice in https://github.com/lidge-jun/opencodex/pull/10",
  "",
  "**Full Changelog**: https://github.com/lidge-jun/opencodex/compare/v1.0.0...v1.1.0",
].join("\n");

describe("selectReleaseBaseline", () => {
  test("skips a newer release that is not reachable from the target", () => {
    // A preview lives on its own lineage. Selecting the newest tag regardless of
    // reachability picked a stable tag on main, the ancestry guard then threw,
    // and no preview could be released once the stable lineage moved ahead.
    // Reproduced against the real repository: without the filter the preview
    // range selected v2.21.0, which is an ancestor of neither preview nor dev.
    const tags = ["v2.17.0", "v2.19.0", "v2.21.0"];
    const reachable = new Set(["v2.17.0", "v2.19.0"]);

    expect(selectReleaseBaseline("2.22.0-preview.1", tags)).toBe("v2.21.0");
    expect(selectReleaseBaseline("2.22.0-preview.1", tags, tag => reachable.has(tag))).toBe("v2.19.0");
  });

  test("the reachability filter applies to stable releases too", () => {
    const tags = ["v2.17.0", "v2.19.0", "v2.21.0"];
    const reachable = new Set(["v2.17.0"]);
    expect(selectReleaseBaseline("2.22.0", tags, tag => reachable.has(tag))).toBe("v2.17.0");
  });

  test("an absent filter preserves the previous selection behavior", () => {
    const tags = ["v2.17.0", "v2.19.0"];
    expect(selectReleaseBaseline("2.20.0", tags)).toBe("v2.19.0");
  });
  test("preview releases are incremental from the previous release", () => {
    expect(selectReleaseBaseline("2.0.0-preview.2", [
      "v1.0.0",
      "v2.0.0-preview.1",
      "v2.0.0-preview.2",
    ])).toBe("v2.0.0-preview.1");
  });

  test("stable releases always baseline the previous stable", () => {
    expect(selectReleaseBaseline("2.18.2", [
      "v2.17.0",
      "v2.17.1-preview.20260814",
      "v2.18.2",
    ])).toBe("v2.17.0");
  });

  test("stable ignores preview core mismatches instead of depending on same-core carry", () => {
    expect(selectReleaseBaseline("2.0.0", [
      "v1.0.0",
      "v1.1.0-preview.1",
      "v1.8.0-preview.4",
    ])).toBe("v1.0.0");
  });

  test("stable ignores every SemVer prerelease, not only preview tags", () => {
    expect(selectReleaseBaseline("2.0.0", [
      "v1.8.0-beta.2",
      "v1.9.0",
      "v2.0.0-preview.1",
      "v2.0.0-rc.1",
    ])).toBe("v1.9.0");
  });

  test("returns null when no earlier release tag exists", () => {
    expect(selectReleaseBaseline("1.0.0", [])).toBeNull();
    expect(selectReleaseBaseline("1.0.0", ["v1.0.0", "v2.0.0"])).toBeNull();
  });
});

describe("commit helpers", () => {
  test("recognizes release-only metadata commits", () => {
    expect(isReleaseMetadataCommit("release: v2.19.0")).toBe(true);
    expect(isReleaseMetadataCommit("chore(release): 2.19.0")).toBe(true);
    expect(isReleaseMetadataCommit("fix(release): keep changelog complete")).toBe(false);
  });

  test("recognizes prereleases from SemVer rather than one channel name", () => {
    expect(isPrereleaseVersion("2.0.0-preview.1")).toBe(true);
    expect(isPrereleaseVersion("v2.0.0-rc.1")).toBe(true);
    expect(isPrereleaseVersion("2.0.0-beta.2")).toBe(true);
    expect(isPrereleaseVersion("2.0.0")).toBe(false);
  });

  test("extracts only a trailing squash-style PR reference", () => {
    expect(trailingLandingPr("fix(api): preserve state (#123)")).toBe(123);
    expect(trailingLandingPr("fix(api): mention #123 in prose")).toBeNull();
  });

  test("matches rendered PR references without accepting longer-number prefixes", () => {
    expect(hasRenderedPullReference("- fixed thing (#155)", 155)).toBe(true);
    expect(hasRenderedPullReference("- unrelated thing (#1553)", 155)).toBe(false);
  });

  test("classifies direct conventional commits into release categories", () => {
    expect(categoryForTitle("feat(api): add a provider")).toBe("New Features");
    expect(categoryForTitle("fix(api): stop a crash")).toBe("Bug Fixes");
    expect(categoryForTitle("docs: explain setup")).toBe("Documentation");
    expect(categoryForTitle("ci: pin an action")).toBe("Chores");
    expect(categoryForTitle("refactor: simplify routing")).toBe("Other Changes");
  });
});

describe("release metadata parsers", () => {
  test("parses multiline git-log records and trailing separators", () => {
    const raw = [
      sha("a"), "fix(core): first change", "fix(core): first change\n\nline one\nline two",
      sha("b"), "feat(api): second change", "feat(api): second change",
      "",
    ].join("\0");

    expect(parseGitLog(raw)).toEqual([
      {
        sha: sha("a"),
        subject: "fix(core): first change",
        body: "fix(core): first change\n\nline one\nline two",
      },
      {
        sha: sha("b"),
        subject: "feat(api): second change",
        body: "feat(api): second change",
      },
    ]);
  });

  test("fails closed on malformed git-log records", () => {
    expect(parseGitLog("")).toEqual([]);
    expect(() => parseGitLog(`\0fix(core): missing sha\0body\0`)).toThrow(
      "malformed release commit record",
    );
    expect(() => parseGitLog(`${sha("a")}\0\0body\0`)).toThrow(
      "malformed release commit record",
    );
    expect(() => parseGitLog(`${sha("a")}\0fix(core): missing body\0`)).toThrow(
      "malformed release commit record",
    );
    expect(() => parseGitLog(`${sha("a")}\0fix(core): truncated\0body`)).toThrow(
      "malformed release commit record",
    );
    expect(() => parseGitLog(`not-a-sha\0fix(core): invalid sha\0body\0`)).toThrow(
      "malformed release commit record",
    );
    expect(() => parseGitLog(`${sha("a")} \0fix(core): padded sha\0body\0`)).toThrow(
      "malformed release commit record",
    );
  });

  test("accepts full SHA-1 and SHA-256 object ids", () => {
    const sha256 = "b".repeat(64);
    const raw = [
      sha("a"), "fix(core): sha-1", "sha-1 body",
      sha256, "fix(core): sha-256", "sha-256 body",
      "",
    ].join("\0");

    expect(parseGitLog(raw).map(item => item.sha)).toEqual([sha("a"), sha256]);
  });

  test("preserves control bytes in commit subjects and bodies", () => {
    const subject = "release: v1.2.3\x1ffix: visible change";
    const body = `${subject}\n\nrecord separator: \x1e`;

    expect(parseGitLog(`${sha("a")}\0${subject}\0${body}\0`)).toEqual([{
      sha: sha("a"),
      subject,
      body,
    }]);
  });

  test("parses actual NUL-delimited git-log output without control-byte collisions", () => {
    const repo = mkdtempSync(join(tmpdir(), "ocx-release-log-"));
    const gitText = (args: string[]): string => {
      const result = Bun.spawnSync(["git", "-C", repo, ...args], {
        stdout: "pipe",
        stderr: "pipe",
      });
      if (result.exitCode !== 0) {
        throw new Error(result.stderr.toString().trim() || `git ${args[0]} failed`);
      }
      return result.stdout.toString();
    };

    try {
      gitText(["init", "--quiet"]);
      const tree = gitText(["write-tree"]).trim();
      const firstSubject = "fix: first \x1f";
      const firstBody = `${firstSubject}\n\nbody \x1e`;
      const firstMessage = join(repo, "first-message.txt");
      writeFileSync(firstMessage, `${firstBody}\n`, "utf8");
      const first = gitText([
        "-c", "user.name=OpenCodex Test",
        "-c", "user.email=test@example.test",
        "commit-tree", tree,
        "-F", firstMessage,
      ]).trim();

      const secondMessage = join(repo, "second-message.txt");
      writeFileSync(secondMessage, "feat: second\n", "utf8");
      const second = gitText([
        "-c", "user.name=OpenCodex Test",
        "-c", "user.email=test@example.test",
        "commit-tree", tree,
        "-p", first,
        "-F", secondMessage,
      ]).trim();

      const raw = gitText([
        "log",
        "--first-parent",
        "--reverse",
        "-z",
        "--format=%H%x00%s%x00%B",
        second,
      ]);
      const fields = raw.split("\0");
      expect(fields.pop()).toBe("");
      expect(fields).toHaveLength(6);
      expect(parseGitLog(raw)).toEqual([
        { sha: first, subject: firstSubject, body: firstBody },
        { sha: second, subject: "feat: second", body: "feat: second" },
      ]);
    } finally {
      removeTreeWithRetry(repo);
    }
  });

  test("normalizes associated pull metadata safely", () => {
    expect(parseAssociatedPulls([
      {
        number: 41,
        title: "fix(core): merged",
        merged_at: "2026-08-15T00:00:00Z",
        user: null,
        labels: [{ name: "bug" }, { name: 123 }, {}],
      },
      {
        number: 42,
        title: "docs: open",
        merged_at: null,
        user: { login: "alice" },
        labels: null,
      },
    ])).toEqual([
      {
        number: 41,
        title: "fix(core): merged",
        author: "unknown",
        labels: ["bug"],
        merged: true,
      },
      {
        number: 42,
        title: "docs: open",
        author: "alice",
        labels: [],
        merged: false,
      },
    ]);
  });
});

describe("buildReleaseNotes", () => {
  test("falls back to direct commits when GitHub generates no PR changelog", () => {
    const result = buildReleaseNotes({
      version: "1.1.0-preview.1",
      tags: ["v1.0.0"],
      npmMetadata: "Published to npm.",
      generatedNotes: "",
      repository: "lidge-jun/opencodex",
      commits: [
        commit("a", "feat(api): add direct feature"),
        commit("b", "fix(gui): fix direct bug"),
      ],
    });

    expect(result.errors).toEqual([]);
    expect(result.baseline).toBe("v1.0.0");
    expect(result.body).toContain("Add direct feature");
    expect(result.body).toContain("Fix direct bug");
    expect(result.body).toContain("aaaaaaaa");
    expect(result.body).toContain("bbbbbbbb");
  });

  test("keeps generated PR notes and adds uncovered direct commits", () => {
    const result = buildReleaseNotes({
      version: "1.1.0",
      tags: ["v1.0.0"],
      npmMetadata: "Published to npm.",
      generatedNotes: generatedBugFix,
      repository: "lidge-jun/opencodex",
      commits: [
        commit("a", "fix(api): preserve generated PR coverage (#10)"),
        commit("b", "fix(responses): include direct fix"),
      ],
    });

    expect(result.errors).toEqual([]);
    expect(result.body).toContain("Preserve generated PR coverage (#10)");
    expect(result.body).toContain("Include direct fix");
    expect(result.body).toContain("bbbbbbbb");
  });

  test("adds a PR fallback when a merged PR is missing from generated notes", () => {
    const result = buildReleaseNotes({
      version: "1.1.0",
      tags: ["v1.0.0"],
      npmMetadata: "Published to npm.",
      generatedNotes: "",
      repository: "lidge-jun/opencodex",
      commits: [
        commit("c", "fix(api): landed through a PR", [
          {
            number: 11,
            title: "fix(api): landed through a PR",
            author: "bob",
            labels: ["bug"],
            merged: true,
          },
        ]),
      ],
    });

    expect(result.errors).toEqual([]);
    expect(result.body).toContain("Landed through a PR (#11)");
    expect(result.body).toContain("- #11 fix(api): landed through a PR @bob");
    expect(result.body).not.toContain("cccccccc");
  });

  test("stable reconstructs every change since the previous stable across mismatched previews", () => {
    const result = buildReleaseNotes({
      version: "2.0.0",
      tags: [
        "v1.0.0",
        "v1.1.0-preview.1",
        "v1.8.0-preview.4",
      ],
      npmMetadata: "Published to npm.",
      generatedNotes: "",
      repository: "lidge-jun/opencodex",
      commits: [
        commit("a", "feat(core): preview change A"),
        commit("b", "fix(core): preview change B"),
        commit("c", "fix(core): post-preview change C"),
        commit("d", "docs: post-preview change D"),
      ],
    });

    expect(result.errors).toEqual([]);
    expect(result.baseline).toBe("v1.0.0");
    expect(result.releasableCommitCount).toBe(4);
    expect(result.body).toContain("Preview change A");
    expect(result.body).toContain("Preview change B");
    expect(result.body).toContain("Post-preview change C");
    expect(result.body).toContain("Post-preview change D");
    expect(result.body).toContain("compare/v1.0.0...v2.0.0");
  });

  test("allows explicit skip-changelog coverage only when another visible change remains", () => {
    const result = buildReleaseNotes({
      version: "1.1.0",
      tags: ["v1.0.0"],
      npmMetadata: "Published to npm.",
      generatedNotes: "",
      repository: "lidge-jun/opencodex",
      commits: [
        commit("a", "chore: internal metadata", [
          {
            number: 12,
            title: "chore: internal metadata",
            author: "bot",
            labels: ["skip-changelog"],
            merged: true,
          },
        ]),
        commit("b", "fix(core): visible fix"),
      ],
    });

    expect(result.errors).toEqual([]);
    expect(result.ignoredCommitCount).toBe(1);
    expect(result.body).toContain("Visible fix");
    expect(result.body).not.toContain("Internal metadata");
  });

  test("fails closed when changed commits would produce an empty changelog", () => {
    const result = buildReleaseNotes({
      version: "1.1.0",
      tags: ["v1.0.0"],
      npmMetadata: "Published to npm.",
      generatedNotes: "",
      repository: "lidge-jun/opencodex",
      commits: [
        commit("a", "chore: hidden change", [
          {
            number: 13,
            title: "chore: hidden change",
            author: "bot",
            labels: ["skip-changelog"],
            merged: true,
          },
        ]),
      ],
    });

    expect(result.errors).toContain(
      "1 changed commit(s) exist, but the changelog has no visible entries",
    );
  });

  test("does not treat the version bump itself as a releasable change", () => {
    const result = buildReleaseNotes({
      version: "1.1.0",
      tags: ["v1.0.0"],
      npmMetadata: "Published to npm.",
      generatedNotes: "",
      repository: "lidge-jun/opencodex",
      commits: [commit("a", "release: v1.1.0")],
    });

    expect(result.errors).toEqual([]);
    expect(result.releasableCommitCount).toBe(0);
  });
  test("sanitizes direct-commit subjects so they cannot inject mentions or media", () => {
    // Commit subjects are author-controlled text rendered as release Markdown.
    // An @mention there rewrites the release's Contributors list, and image
    // syntax renders. PR titles were already cleaned; commits were not.
    const result = buildReleaseNotes({
      version: "1.1.0-preview.1",
      tags: ["v1.0.0"],
      npmMetadata: "Published to npm.",
      generatedNotes: "",
      repository: "lidge-jun/opencodex",
      commits: [
        commit("a", "fix: notify @octocat ![pixel](https://example.invalid/pixel)"),
      ],
    });

    expect(result.errors).toEqual([]);
    // The raw mention must not survive anywhere in the body.
    expect(result.body).not.toContain("@octocat");
    expect(result.body).toContain("@\u200boctocat");
    // Image syntax is escaped rather than rendered.
    expect(result.body).not.toContain("![pixel](https://example.invalid/pixel)");
  });

  test("refuses a non-ancestral baseline for a prerelease, not just a stable release", () => {
    // The ancestry guard used to apply only to stable versions, so a preview
    // could select the newest tag from a diverged lineage and emit that
    // branch's commits while reporting full coverage.
    expect(selectReleaseBaseline("1.2.0-preview.1", ["v1.0.0", "v1.1.0"])).toBe("v1.1.0");
    // The runtime guard is exercised in buildReleaseChangelog; this pins the
    // selection half so a future change cannot quietly widen the candidate set
    // for prereleases without the ancestry check catching it.
    expect(selectReleaseBaseline("1.2.0", ["v1.0.0", "v1.1.0-preview.1"])).toBe("v1.0.0");
  });
});
