import { describe, expect, test } from "bun:test";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { renderManagementSurface } from "../scripts/generate-ocx-skill-surface";
import { CAPABILITIES, HEAD_CAPABILITIES, capabilityInvocation } from "../src/cli/capabilities";
import { CLI_COMMANDS } from "../src/cli/registry";

/**
 * wp8: the repo-owned `ocx` skill.
 *
 * A skill that describes a CLI is a SECOND description of that CLI, free to drift from the first.
 * These tests exist so it cannot: the surface reference is generated and checked, and every command
 * the hand-written pages mention has to exist in the registry.
 *
 * A skill that documents a command nobody can run is worse than no skill, because an agent will
 * try it and conclude the tool is broken.
 */
const SKILL_DIR = join(import.meta.dir, "..", "skills", "ocx");
const SKILL = join(SKILL_DIR, "SKILL.md");
const REFERENCES = [
  "01_management_surface.md",
  "02_json_shapes.md",
  "03_recipes.md",
  "04_failure_semantics.md",
  "05_remote_hub.md",
];

function read(file: string): string {
  return readFileSync(join(SKILL_DIR, file), "utf8");
}

describe("skills/ocx structure", () => {
  test("SKILL.md and every reference exist", () => {
    expect(existsSync(SKILL)).toBe(true);
    for (const ref of REFERENCES) {
      expect(existsSync(join(SKILL_DIR, "references", ref)), ref).toBe(true);
    }
  });

  test("front matter names the skill and carries trigger words", () => {
    const text = readFileSync(SKILL, "utf8");
    expect(text.startsWith("---\n")).toBe(true);
    const front = text.slice(4, text.indexOf("\n---", 4));
    expect(front).toContain("name: ocx");
    expect(front).toContain("description:");
    // Without these it will not activate on the tasks it covers.
    for (const trigger of ["ocx", "opencodex", "account pool", "usage report", "management API"]) {
      expect(front, trigger).toContain(trigger);
    }
  });

  test("SKILL.md routes to every reference it ships", () => {
    const text = readFileSync(SKILL, "utf8");
    for (const ref of REFERENCES) expect(text, ref).toContain(ref);
  });
});

describe("the generated surface reference cannot drift", () => {
  test("the committed file matches regeneration exactly", () => {
    // If this fails, run: bun scripts/generate-ocx-skill-surface.ts
    expect(read("references/01_management_surface.md")).toBe(renderManagementSurface());
  });

  test("it names every declared capability", () => {
    const text = read("references/01_management_surface.md");
    for (const cap of CAPABILITIES) {
      expect(text, capabilityInvocation(cap)).toContain(capabilityInvocation(cap));
    }
    for (const head of HEAD_CAPABILITIES) {
      expect(text, head.invocations[0]).toContain(head.invocations[0]!);
    }
  });

  test("it carries the do-not-edit marker", () => {
    // The marker is the only thing standing between a generated file and a hand-edited one.
    expect(read("references/01_management_surface.md")).toContain("GENERATED by scripts/generate-ocx-skill-surface.ts");
  });
});

describe("documented commands exist", () => {
  /**
   * Every `ocx <word>` that is presented AS A COMMAND, reduced to its top-level name.
   *
   * Only inline code spans and fenced blocks count. Scanning raw prose produced two false
   * positives that are worth remembering: "driving ocx programmatically" (a sentence) and
   * "there is no `ocx request-history` command" -- a line whose entire purpose is to say the
   * command does not exist. A gate that fails on documentation warning you about a missing
   * command is measuring the wrong thing. Inside a code span the string IS a suggested
   * invocation, so the backtick is the signal.
   */
  function documentedCommands(): Set<string> {
    const names = new Set<string>();
    const files = [readFileSync(SKILL, "utf8"), ...REFERENCES.map(r => read(join("references", r)))];
    for (const text of files) {
      const spans: string[] = [];
      // Fenced blocks: everything a reader would copy and run.
      for (const block of text.matchAll(/```[a-z]*\n([\s\S]*?)```/g)) spans.push(block[1]!);
      // Inline code spans, EXCEPT ones a sentence explicitly negates.
      for (const span of text.matchAll(/`([^`\n]+)`/g)) {
        const line = text.slice(text.lastIndexOf("\n", span.index) + 1, text.indexOf("\n", span.index));
        if (/there is no|does not exist|not a command/i.test(line)) continue;
        spans.push(span[1]!);
      }
      for (const span of spans) {
        for (const match of span.matchAll(/\bocx ([a-z][a-z0-9-]*)/g)) names.add(match[1]!);
      }
    }
    return names;
  }

  test("the extractor sees commands inside code, and not command-shaped prose", () => {
    // Guards the gate itself: it must find real invocations, or the assertion below is vacuous.
    const found = documentedCommands();
    for (const expected of ["capabilities", "ready", "status", "logs", "usage", "account", "storage", "inspect"]) {
      expect(found.has(expected), expected).toBe(true);
    }
  });

  test("every ocx <command> named anywhere in the skill is a real command", () => {
    const known = new Set<string>();
    for (const entry of CLI_COMMANDS) {
      known.add(entry.name);
      for (const alias of entry.aliases ?? []) known.add(alias);
    }
    // Head-resolved invocations are not registry entries: they exit before dispatch.
    for (const head of HEAD_CAPABILITIES) {
      for (const invocation of head.invocations) known.add(invocation.replace(/^-+/, ""));
    }

    const unknown = [...documentedCommands()].filter(name => !known.has(name)).sort();
    // A skill that documents a command nobody can run is worse than no skill: an agent will try
    // it and conclude the tool is broken. This is the assertion that caught `ocx request-history`,
    // which the plan named and which does not exist.
    expect(unknown).toEqual([]);
  });
});

describe("the consent boundary is stated, not implied", () => {
  test("SKILL.md forbids starring and does not offer a flag for it", () => {
    const text = readFileSync(SKILL, "utf8");
    expect(text).toContain("Do not star the repository");
    // The failure mode is a skill that mentions the boundary and then hands over a workaround.
    expect(text).not.toMatch(/ocx\s+\S*star\s+--yes/);
  });

  test("no page suggests driving a session-only route another way", () => {
    for (const file of ["SKILL.md", ...REFERENCES.map(r => join("references", r))]) {
      const text = read(file);
      // `gh api` or a raw POST to the star route would be exactly the routing-around this forbids.
      expect(text, file).not.toContain("gh api");
      expect(text, file).not.toMatch(/POST\s+\/api\/github\/star["'`\s]*$/m);
    }
  });

  test("destructive verbs are documented as requiring --yes", () => {
    const skill = readFileSync(SKILL, "utf8");
    const recipes = read("references/03_recipes.md");
    expect(skill).toContain("--yes");
    expect(skill).toContain("no interactive prompt");
    // The preview-first sequence is the operational rule, so it has to appear in the recipes.
    expect(recipes).toContain("PREVIEW");
    expect(recipes).toContain("get approval");
  });
});
