import { afterEach,beforeEach,describe,expect,test } from "bun:test";
import { mkdirSync,readFileSync,utimesSync,writeFileSync } from "node:fs";import{tmpdir}from"node:os";import{join}from"node:path";
import { OAUTH_PROVIDERS,OAuthLoginRequiredError,refreshXaiAccountWithLock } from "../src/oauth";import{XaiTokenRequestError}from"../src/oauth/xai";
import{createOAuthFileLock,createOAuthRefreshIntentLock,getAccountCredential,getAccountSet,getAuthRefreshIntentLockPath,OAuthFileLockError,saveCredential}from"../src/oauth/store";
import { removeTreeWithRetry } from "./helpers/remove-tree";
const oldHome=process.env.HOME,oldOcx=process.env.OPENCODEX_HOME;let root:string;beforeEach(()=>{root=join(tmpdir(),`xai-lock-${crypto.randomUUID()}`);process.env.HOME=root;process.env.OPENCODEX_HOME=join(root,"ocx");mkdirSync(process.env.OPENCODEX_HOME,{recursive:true});});afterEach(()=>{if(oldHome===undefined)delete process.env.HOME;else process.env.HOME=oldHome;if(oldOcx===undefined)delete process.env.OPENCODEX_HOME;else process.env.OPENCODEX_HOME=oldOcx;removeTreeWithRetry(root);});
async function seed(){await saveCredential("xai",{access:"old",refresh:"rotating",expires:1,accountId:"acct"});return getAccountSet("xai")!.activeAccountId;}function def(c:{n:number},gate?:Promise<void>){return{...OAUTH_PROVIDERS.xai!,refresh:async()=>{c.n++;if(gate)await gate;return{access:"fresh",refresh:"next",expires:Date.now()+3600000}}};}
describe("two-lock xAI refresh",()=>{
 test("unrelated writer survives the pre-persist seam",async()=>{const id=await seed(),calls={n:0};let writer!:Promise<void>;await refreshXaiAccountWithLock("xai",id,def(calls),getAccountCredential("xai",id)!,{afterPrePersistRead:()=>{writer=saveCredential("cursor",{access:"c",refresh:"r",expires:Date.now()+1000,accountId:"cursor"})}});await writer;expect(getAccountSet("cursor")?.accounts[0]?.credential.access).toBe("c");expect(getAccountCredential("xai",id)?.refresh).toBe("next");});
 test("same-process writer completes while refresh awaits token I/O",async()=>{const id=await seed();let release!:()=>void;const gate=new Promise<void>(r=>release=r),calls={n:0};const pending=refreshXaiAccountWithLock("xai",id,def(calls,gate),getAccountCredential("xai",id)!);while(!calls.n)await Bun.sleep(1);await saveCredential("cursor",{access:"c",refresh:"r",expires:Date.now()+1000,accountId:"cursor"});release();expect(await pending).toBe("fresh");});
 test("two independent lock instances perform one IdP call",async()=>{const id=await seed();let release!:()=>void;const gate=new Promise<void>(r=>release=r),calls={n:0},stale=getAccountCredential("xai",id)!;const a=refreshXaiAccountWithLock("xai",id,def(calls,gate),stale,{intentLock:createOAuthRefreshIntentLock("xai",id)});while(!calls.n)await Bun.sleep(1);const b=refreshXaiAccountWithLock("xai",id,def(calls),stale,{intentLock:createOAuthRefreshIntentLock("xai",id)});release();expect(await Promise.all([a,b])).toEqual(["fresh","fresh"]);expect(calls.n).toBe(1);});
 test("lock timeout is typed",async()=>{const id=await seed(),held=await createOAuthRefreshIntentLock("xai",id).acquire();try{await expect(createOAuthRefreshIntentLock("xai",id,{waitTimeoutMs:0}).acquire()).rejects.toBeInstanceOf(OAuthFileLockError);}finally{held.release();}});
 test("stale takeover and replacement-safe release",async()=>{const p=getAuthRefreshIntentLockPath("xai","acct");writeFileSync(p,JSON.stringify({version:1,ownerId:"old",pid:1,createdAt:0}));utimesSync(p,new Date(0),new Date(0));const g=await createOAuthFileLock({path:p,staleAfterMs:1}).acquire();const replacement=JSON.stringify({version:1,ownerId:"new",pid:2,createdAt:Date.now()});writeFileSync(p,replacement);g.release();expect(readFileSync(p,"utf8")).toBe(replacement);});
 test("partial metadata failure cleans its inode",async()=>{const p=getAuthRefreshIntentLockPath("xai","acct");await expect(createOAuthFileLock({path:p,writeMetadata:fd=>{writeFileSync(fd,"{");throw new Error("partial")}}).acquire()).rejects.toBeInstanceOf(OAuthFileLockError);expect(()=>readFileSync(p)).toThrow();});
 test("replacement between stale inspections survives",async()=>{const p=getAuthRefreshIntentLockPath("xai","acct");const fixedNow=Date.now();writeFileSync(p,JSON.stringify({version:1,ownerId:"old",pid:1,createdAt:0}));utimesSync(p,new Date(0),new Date(0));const replacement=JSON.stringify({version:1,ownerId:"new",pid:2,createdAt:fixedNow});await expect(createOAuthFileLock({path:p,staleAfterMs:1,waitTimeoutMs:0,now:()=>fixedNow,beforeStaleUnlink:()=>writeFileSync(p,replacement)}).acquire()).rejects.toBeInstanceOf(OAuthFileLockError);expect(readFileSync(p,"utf8")).toBe(replacement);});
 test("same-account replacement during exchange wins",async()=>{const id=await seed();let release!:()=>void;const gate=new Promise<void>(r=>release=r),calls={n:0},stale=getAccountCredential("xai",id)!;const pending=refreshXaiAccountWithLock("xai",id,def(calls,gate),stale);while(!calls.n)await Bun.sleep(1);await saveCredential("xai",{access:"writer",refresh:"writer-gen",expires:Date.now()+3600000,accountId:"acct"});release();expect(await pending).toBe("writer");expect(getAccountCredential("xai",id)?.refresh).toBe("writer-gen");});
 test("terminal failure does not mark replaced generation",async()=>{const id=await seed();let reject!:()=>void,calls=0;const gate=new Promise<never>((_,r)=>reject=()=>r(new XaiTokenRequestError(400,"invalid_grant","bad")));const stale=getAccountCredential("xai",id)!;const pending=refreshXaiAccountWithLock("xai",id,{...OAUTH_PROVIDERS.xai!,refresh:async()=>{calls++;return gate}},stale);while(!calls)await Bun.sleep(1);await saveCredential("xai",{access:"writer",refresh:"writer-gen",expires:Date.now()+3600000,accountId:"acct"});reject();await expect(pending).rejects.toBeInstanceOf(OAuthLoginRequiredError);expect(getAccountSet("xai")!.accounts[0]!.needsReauth).toBeUndefined();});
 test("permanent verdict TTL is generation scoped",async()=>{const id=await seed();await saveCredential("xai",{access:"ttl-old",refresh:"ttl-rotating",expires:1,accountId:"acct"});const credential=getAccountCredential("xai",id)!;let now=1000,calls=0;const bad={...OAUTH_PROVIDERS.xai!,refresh:async()=>{calls++;throw new XaiTokenRequestError(400,"invalid_grant","bad")}};await expect(refreshXaiAccountWithLock("xai",id,bad,credential,{now:()=>now})).rejects.toThrow();await expect(refreshXaiAccountWithLock("xai",id,bad,credential,{now:()=>now})).rejects.toThrow();expect(calls).toBe(1);now+=30001;await expect(refreshXaiAccountWithLock("xai",id,bad,credential,{now:()=>now})).rejects.toThrow();expect(calls).toBe(2);await saveCredential("xai",{...credential,access:"new",refresh:"new-r",expires:now+100000});expect(await refreshXaiAccountWithLock("xai",id,bad,credential,{now:()=>now})).toBe("new");});
});
