import type { OcxProviderConfig } from "../types";

// Every provider field receives a deliberate identity role. A new field fails typecheck
// until its model-id semantics are classified; credentials and provider-wide policy are none.
type ModelRenameRole = "none" | "record" | "list" | "scalar" | "nested-models";
export const PROVIDER_MODEL_RENAME_ROLES = {
  alias: "none",
  modelAliases: "record",
  modelDisplayNames: "record",
  defaultAliases: "none",
  adapter: "none",
  codexToolMode: "none",
  requestPacing: "nested-models",
  mcpMaxTools: "none",
  mcpMaxSchemaBytes: "none",
  mcpMaxResultBytes: "none",
  modelAdapters: "record",
  fastWire: "none",
  baseUrl: "none",
  responsesPath: "none",
  chatCompletionsPath: "none",
  commandCodeVersion: "none",
  statelessResponses: "none",
  requiresAdjacentResponsesToolResults: "none",
  requiresPairedResponsesToolResults: "none",
  annotateEmptyToolOutputs: "none",
  supportsServiceTier: "none",
  fastEnabled: "none",
  modelSupportsServiceTier: "record",
  preserveResponsesReasoningContent: "none",
  modelReasoningEffortsAuthoritative: "none",
  dropResponsesReasoningItems: "none",
  decodesNativeCompactionBlobs: "none",
  allowEncryptedV2AgentTasks: "none",
  allowPrivateNetwork: "none",
  proxy: "none",
  noProxy: "none",
  upstreamHttpVersion: "none",
  upstreamWebsocket: "none",
  directGeminiWireRenames: "none",
  disabled: "none",
  codexAccountMode: "none",
  apiKey: "none",
  apiKeyTransport: "none",
  apiKeyPool: "none",
  apiKeyPoolStrategy: "none",
  apiKeySelectionRevision: "none",
  _apiKeyAttempt: "none",
  defaultModel: "scalar",
  models: "list",
  liveModels: "none",
  selectedModels: "list",
  initialModelSelection: "none",
  retainModels: "list",
  newModelPolicy: "none",
  modelPreset: "none",
  contextWindow: "none",
  modelContextWindows: "record",
  modelInputModalities: "record",
  modelCapabilities: "record",
  modelMaxInputTokens: "record",
  modelAutoCompactTokenLimits: "record",
  defaultMaxOutputTokens: "none",
  modelMaxOutputTokens: "record",
  modelCosts: "record",
  autoReviewModel: "none",
  autoReviewModelOverrides: "record",
  headers: "none",
  openRouterRouting: "none",
  modelOpenRouterRouting: "record",
  vercelGatewayRouting: "none",
  modelVercelGatewayRouting: "record",
  authMode: "none",
  oauthAccountFailover: "none",
  keyOptional: "none",
  freeTier: "none",
  note: "none",
  modelSuffixBracketStrip: "none",
  refreshPolicy: "none",
  reasoningEfforts: "none",
  modelReasoningEfforts: "record",
  modelSuppressSyntheticMax: "record",
  modelDefaultReasoningEfforts: "record",
  pinnedReasoningEffort: "none",
  modelPinnedReasoningEfforts: "record",
  modelSupportsReasoningSummaries: "record",
  modelSupportsVerbosity: "record",
  supportsVerbosity: "none",
  modelReasoningSummaryDelivery: "record",
  modelPreferHostedTools: "record",
  supportsOpenAiWebSearchToolFields: "none",
  xaiResponsesXSearch: "none",
  xaiResponsesDefaultVersion: "none",
  zaiResponsesDefaultVersion: "none",
  supportsResponsesCustomTools: "none",
  unsupportedHostedTools: "none",
  responsesSnapshotRepair: "none",
  webSearchBridge: "none",
  reasoningEffortMap: "none",
  modelReasoningEffortMap: "record",
  reasoningWireFormat: "none",
  noReasoningModels: "list",
  noTemperatureModels: "list",
  noTopPModels: "list",
  noStopModels: "list",
  noPenaltyModels: "list",
  noStructuredOutputModels: "list",
  noJsonSchemaModels: "list",
  omitReasoningEffortWithToolsModels: "list",
  parallelToolCalls: "none",
  pinParallelToolCallsFalse: "none",
  terminalContinuationGuard: "none",
  openaiChatEofTolerance: "none",
  foldDeveloperRoleToSystem: "none",
  promptCacheKey: "none",
  chatServiceTier: "none",
  responsesItemIdRepair: "none",
  autoToolChoiceOnlyModels: "list",
  preserveReasoningContentModels: "list",
  requiresReasoningPlaceholderModels: "list",
  showThinkingSummary: "none",
  retryOn429: "none",
  transientRetryOn5xx: "none",
  retryOnReset: "none",
  reasoningSplitModels: "list",
  inlineThinkTagModels: "list",
  reasoningDetailsModels: "list",
  thinkingToggleModels: "list",
  thinkingBudgetModels: "list",
  escapeBuiltinToolNames: "none",
  anthropicEofTolerance: "none",
  noVisionModels: "list",
  googleMode: "none",
  googleToolSchemaPolicy: "none",
  project: "none",
  location: "none",
  mcpServers: "none",
  desktopExecutor: "none",
  unsafeAllowNativeLocalExec: "none",
  nativeLocalExec: "none",
} as const satisfies Record<keyof OcxProviderConfig, ModelRenameRole>;

function fieldsWithRole(role: ModelRenameRole): string[] {
  return Object.entries(PROVIDER_MODEL_RENAME_ROLES).filter(([, value]) => value === role).map(([key]) => key);
}
export const MODEL_KEYED_RECORDS = fieldsWithRole("record");
// Legacy persisted registry field, no longer part of the public provider config interface.
export const MODEL_ID_LISTS = [...fieldsWithRole("list"), "directReasoningEffortModels"];
export const MODEL_ID_SCALARS = fieldsWithRole("scalar");
export const MODEL_NESTED_RECORDS = fieldsWithRole("nested-models");
