import type { Capability } from "./capability-types";

export const LAB_CAPABILITIES: readonly Capability[] = [
  {
    command: ["lab", "status"],
    usage: "ocx lab status [--json]",
    summary: "Read local Lab projection status.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied."],
  },
  {
    command: ["lab", "verdicts"],
    usage: "ocx lab verdicts [--subject <subject>] [--layer <layer>] [--suite <suite>] [--verdict <verdict>] [--from <ms>] [--to <ms>] [--limit <n>] [--cursor <cursor>] [--json]",
    summary: "Read local Lab verdicts.",
    routes: [],
    flags: [{"name": "--subject", "value": "string", "summary": "Exact subject ID."}, {"name": "--layer", "value": "string", "summary": "Evidence layer."}, {"name": "--suite", "value": "string", "summary": "Suite ID."}, {"name": "--verdict", "value": "string", "summary": "Compatibility verdict."}, {"name": "--from", "value": "number", "summary": "Inclusive timestamp in milliseconds."}, {"name": "--to", "value": "number", "summary": "Timestamp upper bound in milliseconds."}, {"name": "--limit", "value": "number", "summary": "Positive page size."}, {"name": "--cursor", "value": "string", "summary": "Opaque page cursor."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Read commands do not start probes or scheduler ticks."],
  },
  {
    command: ["lab", "subjects"],
    usage: "ocx lab subjects [--kind <kind>] [--limit <n>] [--cursor <cursor>] [--json]",
    summary: "Read local Lab subjects.",
    routes: [],
    flags: [{"name": "--kind", "value": "string", "summary": "Subject kind."}, {"name": "--limit", "value": "number", "summary": "Positive page size."}, {"name": "--cursor", "value": "string", "summary": "Opaque page cursor."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Read commands do not start probes or scheduler ticks."],
  },
  {
    command: ["lab", "observations"],
    usage: "ocx lab observations [--subject <subject>] [--layer <layer>] [--suite <suite>] [--scenario <scenario>] [--outcome <outcome>] [--execution-mode <execution-mode>] [--from <ms>] [--to <ms>] [--limit <n>] [--cursor <cursor>] [--json]",
    summary: "Read local Lab observations.",
    routes: [],
    flags: [{"name": "--subject", "value": "string", "summary": "Exact subject ID."}, {"name": "--layer", "value": "string", "summary": "Evidence layer."}, {"name": "--suite", "value": "string", "summary": "Suite ID."}, {"name": "--scenario", "value": "string", "summary": "Scenario ID."}, {"name": "--outcome", "value": "string", "summary": "Observation outcome."}, {"name": "--execution-mode", "value": "string", "summary": "Execution mode."}, {"name": "--from", "value": "number", "summary": "Inclusive timestamp in milliseconds."}, {"name": "--to", "value": "number", "summary": "Timestamp upper bound in milliseconds."}, {"name": "--limit", "value": "number", "summary": "Positive page size."}, {"name": "--cursor", "value": "string", "summary": "Opaque page cursor."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Read commands do not start probes or scheduler ticks."],
  },
  {
    command: ["lab", "events"],
    usage: "ocx lab events [--event-kind <event-kind>] [--subject <subject>] [--from <ms>] [--to <ms>] [--excluded <true|false>] [--limit <n>] [--cursor <cursor>] [--json]",
    summary: "Read local Lab events.",
    routes: [],
    flags: [{"name": "--event-kind", "value": "string", "summary": "Event kind."}, {"name": "--subject", "value": "string", "summary": "Exact subject ID."}, {"name": "--from", "value": "number", "summary": "Inclusive timestamp in milliseconds."}, {"name": "--to", "value": "number", "summary": "Timestamp upper bound in milliseconds."}, {"name": "--excluded", "value": "string", "summary": "true or false; takes a value."}, {"name": "--limit", "value": "number", "summary": "Positive page size."}, {"name": "--cursor", "value": "string", "summary": "Opaque page cursor."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Read commands do not start probes or scheduler ticks."],
  },
  {
    command: ["lab", "artifacts"],
    usage: "ocx lab artifacts [--status <status>] [--artifact-class <artifact-class>] [--limit <n>] [--cursor <cursor>] [--json]",
    summary: "Read local Lab artifacts.",
    routes: [],
    flags: [{"name": "--status", "value": "string", "summary": "present, corrupt or purged_unavailable."}, {"name": "--artifact-class", "value": "string", "summary": "Artifact class."}, {"name": "--limit", "value": "number", "summary": "Positive page size."}, {"name": "--cursor", "value": "string", "summary": "Opaque page cursor."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Read commands do not start probes or scheduler ticks."],
  },
  {
    command: ["lab", "catalog"],
    usage: "ocx lab catalog [--layer <layer>] [--suite <suite>] [--json]",
    summary: "Read local Lab catalog.",
    routes: [],
    flags: [{"name": "--layer", "value": "string", "summary": "Evidence layer."}, {"name": "--suite", "value": "string", "summary": "Suite ID."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Read commands do not start probes or scheduler ticks."],
  },
  {
    command: ["lab", "subject"],
    usage: "ocx lab subject <subjectId> [--json]",
    summary: "Inspect one local Lab subject.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied."],
  },
  {
    command: ["lab", "event"],
    usage: "ocx lab event <eventId> [--json]",
    summary: "Inspect one local Lab event.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied."],
  },
  {
    command: ["lab", "artifact"],
    usage: "ocx lab artifact <digest> [--json]",
    summary: "Inspect one local Lab artifact.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied."],
  },
  {
    command: ["lab", "production-signals"],
    usage: "ocx lab production-signals --subject <id> [--limit <n>] [--json]",
    summary: "Read passive production context for one exact Lab route subject.",
    routes: [],
    flags: [{"name": "--subject", "value": "string", "summary": "Exact Lab route subject ID.", "required": true}, {"name": "--limit", "value": "number", "summary": "Positive page size."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Passive production context is not verification evidence."],
  },
  {
    command: ["lab", "public", "preview"],
    usage: "ocx lab public preview --event <eventId> [--event <eventId> ...] [--json]",
    summary: "Preview unsigned local public evidence.",
    routes: [],
    flags: [{"name": "--event", "value": "string", "summary": "Event ID; repeat for multiple records.", "required": true}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "No remote publishing occurs. Preview creates no publisher key; export can create local signing identity and bundle files."],
  },
  {
    command: ["lab", "public", "export"],
    usage: "ocx lab public export --event <eventId> [--event <eventId> ...] [--json]",
    summary: "Export signed local public evidence.",
    routes: [],
    flags: [{"name": "--event", "value": "string", "summary": "Event ID; repeat for multiple records.", "required": true}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "No remote publishing occurs. Preview creates no publisher key; export can create local signing identity and bundle files."],
  },
  {
    command: ["lab", "public", "verify"],
    usage: "ocx lab public verify --file <bundle.json> [--json]",
    summary: "Verify a public evidence file.",
    routes: [],
    flags: [{"name": "--file", "value": "string", "summary": "Public evidence bundle path.", "required": true}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Signature validity proves integrity/continuity, not local verification.", "A verification failure emits its structured summary and then returns nonzero."],
  },
  {
    command: ["lab", "public", "import"],
    usage: "ocx lab public import --file <bundle.json> [--json]",
    summary: "Import public evidence as untrusted community context.",
    routes: [],
    flags: [{"name": "--file", "value": "string", "summary": "Public evidence bundle path.", "required": true}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Signature validity proves integrity/continuity, not local verification.", "Imported community evidence never becomes locally verified evidence."],
  },
  {
    command: ["lab", "public", "community"],
    usage: "ocx lab public community [--json]",
    summary: "List local untrusted community evidence context.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied."],
  },
  {
    command: ["lab", "automation", "status"],
    usage: "ocx lab automation [status] [--json]",
    summary: "Read local automation policy, queue and run state.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied."],
  },
  {
    command: ["lab", "automation", "enable"],
    usage: "ocx lab automation enable [--protocol] [--live] [--json]",
    summary: "Enable local Lab automation layers.",
    routes: [],
    flags: [{"name": "--protocol", "value": "boolean", "summary": "Select protocol conformance."}, {"name": "--live", "value": "boolean", "summary": "Select live route compatibility; may spend upstream quota."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "These flags already exist in the local handler. With neither flag, preserve current layer selection; with either flag, select only requested layers.", "Persists local policy, reconciles the queue and starts a scheduler in this CLI process; this is not a remote scheduler control API. Task-effectiveness background remains disabled."],
  },
  {
    command: ["lab", "automation", "disable"],
    usage: "ocx lab automation disable [--json]",
    summary: "Disable local Lab automation.",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "Persists disabled policy, reconciles the local queue and stops this process scheduler."],
  },
  {
    command: ["lab", "automation", "runs"],
    usage: "ocx lab automation runs [--limit <n>] [--cursor <c>] [--json]",
    summary: "List locally persisted automation runs.",
    routes: [],
    flags: [{"name": "--limit", "value": "number", "summary": "Positive page size."}, {"name": "--cursor", "value": "string", "summary": "Opaque page cursor."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: false,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied."],
  },
  {
    command: ["lab", "run"],
    usage: "ocx lab run --layer <protocol_conformance|live_route_compatibility|task_effectiveness> --scenario <id> [--provider <name>] [--model <id>] [--json]",
    summary: "Plan and enqueue an explicit local Lab run.",
    routes: [],
    flags: [{"name": "--layer", "value": "string", "summary": "Evidence layer.", "required": true}, {"name": "--scenario", "value": "string", "summary": "Scenario ID.", "required": true}, {"name": "--provider", "value": "string", "summary": "Configured provider name."}, {"name": "--model", "value": "string", "summary": "Model ID."}, {"name": "--json", "value": "boolean", "summary": "Emit the local result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Local Lab helpers and storage only; no management HTTP. Remote/live-proxy equivalence is not implied.", "The live-route layer installs a production route executor and can spend upstream quota. Explicit operator authorization is required for probes.", "An enqueued run receipt is not a completed verification. No run-cancel or full policy/routes editor is claimed."],
  },
];
