import type { Capability } from "./capability-types";

/** Verified existing handlers only; local operations never claim management routes. */
export const ACCESS_REMOTE_CAPABILITIES: readonly Capability[] = [
  {
    command: ["access", "key"], summary: "Manage API access keys and inspect masked metadata.",
    usage: "ocx access key list [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}, {"method": "POST", "path": "/api/keys"}, {"method": "PATCH", "path": "/api/keys"}, {"method": "DELETE", "path": "/api/keys"}, {"method": "POST", "path": "/api/keys/rotate"}, {"method": "POST", "path": "/api/keys/rotate/commit"}, {"method": "DELETE", "path": "/api/keys/rotate"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Mixed family: list/get read masked metadata; scope edits, revocation and rotation change authorization.", "Creation and rotation initiation return plaintext secrets once and are human-only handoffs. Ask the operator to perform them in their terminal or dashboard; never capture the returned credential.", "Use the separately documented safe follow-up leaves. keys and top-level api-key are aliases."],
  },
  {
    command: ["access", "key", "list"], summary: "List masked access keys, usage, endpoints and pending rotations.",
    usage: "ocx access key list [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false, json: "payload",
    details: ["No plaintext secret is returned by the list route."],
  },
  {
    command: ["access", "key", "get"], summary: "Read one masked key and its access scope.",
    usage: "ocx access key get <id-or-name> [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false, json: "payload",
    details: ["Case-insensitive ID takes precedence over name; ambiguous names are refused."],
  },
  {
    command: ["access", "key", "set"], summary: "Replace selected provider/model scope dimensions.",
    usage: "ocx access key set <id-or-name> [--allow-provider <name>]... [--allow-model <id>]... [--clear] [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}, {"method": "PATCH", "path": "/api/keys"}],
    flags: [{"name": "--allow-provider", "value": "string", "summary": "Provider scope; repeatable, replaces that dimension."}, {"name": "--allow-model", "value": "string", "summary": "Model scope; repeatable, replaces that dimension."}, {"name": "--clear", "value": "boolean", "summary": "Clear both dimensions; submitted allow options then override their dimension."}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["At least one scope option is required. Unspecified dimensions are preserved; this command does not rename keys."],
  },
  {
    command: ["access", "key", "rotate", "commit"], summary: "Commit a pending key rotation.",
    usage: "ocx access key rotate commit <id> <rotation-id> [--json]",
    routes: [{"method": "POST", "path": "/api/keys/rotate/commit"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Use IDs from the human-authorized rotation. Commit only after the client accepts the replacement; the old credential is retired."],
  },
  {
    command: ["access", "key", "rotate", "abort"], summary: "Abort a pending key rotation.",
    usage: "ocx access key rotate abort <id> <rotation-id> [--json]",
    routes: [{"method": "DELETE", "path": "/api/keys/rotate"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Use IDs from the human-authorized rotation. Abort discards the pending replacement credential."],
  },
  {
    command: ["access", "key", "remove"], summary: "Revoke one API access key.",
    usage: "ocx access key remove <id> --yes [--json]",
    routes: [{"method": "DELETE", "path": "/api/keys"}],
    flags: [{"name": "--yes", "value": "boolean", "summary": "Required confirmation before revoking the key.", "required": true}, {"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: true, json: "payload",
    details: ["Uses the exact ID, not name resolution; delete is an alias."],
  },
  {
    command: ["access", "endpoints"], summary: "Read endpoint URLs from the access-key metadata.",
    usage: "ocx access endpoints [--json]",
    routes: [{"method": "GET", "path": "/api/keys"}],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false, json: "envelope",
    details: ["Projects only baseUrl, endpoint and fields ending in Endpoint; use key list for the full metadata payload."],
  },
  {
    command: ["access", "models"], summary: "Read the public external-model catalog.",
    usage: "ocx access models [--json]",
    routes: [],
    flags: [{"name": "--json", "value": "boolean", "summary": "Emit the result as JSON."}],
    mutates: false, json: "payload",
    details: ["Data-plane GET /v1/models via the runtime client; differs from management models live. The routes field indexes management API routes only."],
  },
  {
    command: ["access","test"],
    summary: "Send a small inference request through the selected protocol.",
    usage: "ocx access test <model> [--protocol <chat|responses|messages>] [--api-key-stdin] [--json]",
    routes: [],
    flags: [{"name":"--protocol","value":"string","summary":"chat | responses | messages; default chat."},{"name":"--json","value":"boolean","summary":"Emit the result as JSON."},{"name":"--api-key-stdin","value":"boolean","summary":"Read one explicit data key from bounded piped stdin; no secret argv/env or management/enrolled-key fallback."}],
    mutates: true,
    json: "envelope",
    details: ["Data-plane model POSTs are not management routes. The request may spend provider quota; run only for an explicitly authorized model probe. Legacy unkeyed behavior/JSON remains unchanged.","Explicit-key mode first sends a credentialless malformed-body control to the same protocol endpoint. Only the native key-required401 permits one16-token keyed request. Authless/unrecognized targets refuse before inference.","Version1 selected-key JSON reports control/request observations and a safe text/completion/usage projection. Limited output stays limited; neither control nor response certifies billing identity, key scopes or atomic policy stability.","Keys use explicit bounded stdin and printableASCII input compatible with issued keys. Same-target identity checks, deadlines, redirect refusal, exact-key redaction and cancellation apply; no retries or fallback credential."],
  },
  {
    command: ["remote-workspace","hub","status"],
    usage: "ocx remote-workspace hub status [--json]",
    summary: "Read Hub devices, runtime availability and sessions.",
    routes: [{"method":"GET","path":"/api/remote-workspace"}],
    flags: [{"name":"--json","value":"boolean","summary":"Emit one validated task result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["Existing remote-workspace status remains executor-local. These fixed reads use the selected management Hub; they do not create pairing grants, sessions or remote commands.","Available empty lists succeed. Disabled Hub observations return explicit available:false and exit1; malformed or refused responses are not presented as empty success. Runtime reads can perform availability probes."],
  },
  {
    command: ["remote-workspace","hub","runtimes"],
    usage: "ocx remote-workspace hub runtimes [--json]",
    summary: "Read Codex, Claude and Pi availability on the Hub.",
    routes: [{"method":"GET","path":"/api/remote-workspace/runtimes"}],
    flags: [{"name":"--json","value":"boolean","summary":"Emit one validated task result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["Existing remote-workspace status remains executor-local. These fixed reads use the selected management Hub; they do not create pairing grants, sessions or remote commands.","Available empty lists succeed. Disabled Hub observations return explicit available:false and exit1; malformed or refused responses are not presented as empty success. Runtime reads can perform availability probes."],
  },
  {
    command: ["remote-workspace","hub","sessions"],
    usage: "ocx remote-workspace hub sessions [--json]",
    summary: "Read Hub sessions and their public recent events.",
    routes: [{"method":"GET","path":"/api/remote-workspace/sessions"}],
    flags: [{"name":"--json","value":"boolean","summary":"Emit one validated task result as JSON."}],
    mutates: false,
    json: "payload",
    details: ["Existing remote-workspace status remains executor-local. These fixed reads use the selected management Hub; they do not create pairing grants, sessions or remote commands.","Available empty lists succeed. Disabled Hub observations return explicit available:false and exit1; malformed or refused responses are not presented as empty success. Runtime reads can perform availability probes."],
  },
  {
    command: ["access","key","rename"],
    usage: "ocx access key rename <id-or-name> <name> [--json]",
    summary: "Rename an unambiguously selected API key while preserving its scopes.",
    routes: [{"method":"GET","path":"/api/keys"},{"method":"PATCH","path":"/api/keys"}],
    flags: [{"name":"--json","value":"boolean","summary":"Emit the command result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["Resolves a unique ID/name from the pinned management roster and sends only id/name. Duplicate-ID ambiguity is refused; no plaintext, scope clear, rotation or deletion is involved.","Name follows existing trimmed nonempty64-unit/control-character rules. Resolution is not revision CAS; API-key root alias shares the operation."],
  },
  {
    command: ["access","audio","transcribe"],
    usage: "ocx access audio transcribe <file> --model <gpt-4o-transcribe|gpt-4o-mini-transcribe|whisper-1> --api-key-stdin [--json]",
    summary: "Transcribe an explicitly chosen bounded audio file with a supplied data key.",
    routes: [],
    flags: [{"name":"--model","value":"string","summary":"Required supported transcription model; no silent model fallback.","required":true},{"name":"--api-key-stdin","value":"boolean","summary":"Required bounded explicit data key on piped stdin; no management/enrolled-key substitution.","required":true},{"name":"--json","value":"boolean","summary":"Emit the command result as JSON."}],
    mutates: true,
    json: "payload",
    details: ["Fixed data-plane POST /v1/audio/transcriptions with file/model/response_format=json. May use provider quota; requires explicit upload/inference authority.","File must be nonempty regular input≤25,000,000bytes; multipart≤32MiB, response≤2MiB, request130s. Only the requested text result is returned, with exact supplied-key redaction.","Audio uses its own explicit-key admission, including on an otherwise authless model listener. No generic model control, retries, secret argv/env or redirect following."],
  },
  {
    command: ["access","audio","live-check"],
    usage: "ocx access audio live-check --model <id> --api-key-stdin [--json]",
    summary: "Check actual live-session readiness, then close the connection.",
    routes: [],
    flags: [{"name":"--model","value":"string","summary":"Required live model; sent to the existing live route.","required":true},{"name":"--api-key-stdin","value":"boolean","summary":"Required bounded printableASCII key, encoded only in the established audio subprotocol.","required":true},{"name":"--json","value":"boolean","summary":"Emit the command result as JSON."}],
    mutates: true,
    json: "envelope",
    details: ["Fixed data-plane WebSocket /v1/live with the existing audio key carrier and session.update, then session.close. It contacts upstream and may incur provider usage; no microphone, audio upload, tool execution or voice-roundtrip claim.","Version1 report distinguishes readiness from confirmed normal close. Socket-open alone is not ready.15s readiness,2s close deadline; stuck/abnormal closure remains unverified/nonzero, with local socket termination.","No raw frames/session IDs/encoded credentials are printed. NativeWebSocket redirect refusal is verified separately from HTTP upload behavior."],
  },
];
