import { describe, expect, test } from "bun:test";
import { cpSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { CAPABILITIES, HEAD_CAPABILITIES, capabilityInvocation } from "../../src/cli/capabilities";
import { renderManagementSurfaces } from "../../scripts/generate-ocx-skill-surface";
import { CAPABILITY_DATA_FILES } from "../helpers/cli-capability-data";
import { repoPath } from "../helpers/repo-root";

const INDEX = "01_management_surface.md";
const OWNER = "GENERATED by scripts/generate-ocx-skill-surface.ts";
// Audited navigation contract, independent of the generator's internal assignment helper.
const GROUPS: Record<string, string[]> = {
  lifecycle: ["chatgpt", "status", "resolve", "capabilities", "sync", "start", "stop", "restart", "service", "gui"],
  "providers-models": ["provider", "models", "alias"], accounts: ["account", "auth", "login", "logout"],
  "agents-routing": ["agent", "combo", "route", "v2", "effort", "memory", "message"], integrations: ["claude", "integration", "commandcode", "grok", "codex-shim"],
  "observe-system": ["companion", "usage", "logs", "storage", "inspect", "system", "observe", "debug", "export", "import", "cost", "update", "config", "tray"],
  "access-remote": ["link", "remote-workspace", "hub", "connect", "api", "access"], lab: ["lab"],
};
const FILENAMES = [INDEX, ...Object.keys(GROUPS).map(domain => `01_surface_${domain}.md`)];
const SKILL_DIR = repoPath("skills", "ocx");

function headings(text: string): string[] {
  return [...text.matchAll(/^#{1,6} (.+)$/gm)].map(match => match[1]!
    .toLowerCase().replace(/[^\p{L}\p{N}_ -]/gu, "").replaceAll(" ", "-"));
}

function documents(directory: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const file = join(directory, entry.name);
    if (entry.isDirectory()) Object.assign(files, documents(file));
    else if (entry.name.endsWith(".md")) files[file] = readFileSync(file, "utf8");
  }
  return files;
}

/** Check local Markdown links, then traverse from SKILL. Both file and fragment are required. */
function navigationErrors(files: Record<string, string>, start: string): string[] {
  const errors: string[] = [];
  const edges = new Map<string, string[]>();
  for (const [file, text] of Object.entries(files)) {
    const targets: string[] = [];
    for (const match of text.matchAll(/\[[^\]]+\]\(([^)\s]+)\)/g)) {
      const href = match[1]!;
      if (/^[a-z]+:/i.test(href)) continue;
      const [path, fragment] = href.split("#");
      const target = path ? resolve(dirname(file), path) : file;
      if (files[target] === undefined) errors.push(`${file}: missing file ${href}`);
      else if (fragment && !headings(files[target]!).includes(decodeURIComponent(fragment))) {
        errors.push(`${file}: missing anchor ${href}`);
      }
      targets.push(target);
    }
    edges.set(file, targets);
  }
  const reached = new Set<string>();
  const visit = (file: string) => {
    if (reached.has(file)) return;
    reached.add(file);
    for (const next of edges.get(file) ?? []) visit(next);
  };
  visit(start);
  for (const file of Object.keys(files)) if (!reached.has(file)) errors.push(`unreachable: ${file}`);
  return errors;
}

// The generator runs unchanged in a temporary tree. No repository files or shared metadata
// are mutated; present-usage/invalid declarations live only in a fresh subprocess instance.
function withGenerator(run: (root: string, references: string) => void): void {
  const root = mkdtempSync(join(tmpdir(), "ocx-skill-surface-"));
  try {
    const references = join(root, "skills", "ocx", "references");
    mkdirSync(references, { recursive: true });
    mkdirSync(join(root, "scripts"));
    mkdirSync(join(root, "src", "cli"), { recursive: true });
    cpSync(repoPath("scripts", "generate-ocx-skill-surface.ts"), join(root, "scripts", "generate-ocx-skill-surface.ts"));
    for (const name of CAPABILITY_DATA_FILES) {
      cpSync(repoPath("src", "cli", name), join(root, "src", "cli", name));
    }
    run(root, references);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

function generate(root: string, ...args: string[]) {
  const result = Bun.spawnSync([process.execPath, "scripts/generate-ocx-skill-surface.ts", ...args], {
    cwd: root, stdout: "pipe", stderr: "pipe",
  });
  return { status: result.exitCode, stdout: result.stdout.toString(), stderr: result.stderr.toString() };
}

function renderFixture(root: string, mutation: string) {
  const result = Bun.spawnSync([process.execPath, "-e", `
    import { CAPABILITIES } from "./src/cli/capabilities";
    import { renderManagementSurfaces } from "./scripts/generate-ocx-skill-surface";
    ${mutation}
    console.log(JSON.stringify(renderManagementSurfaces()));
  `], { cwd: root, stdout: "pipe", stderr: "pipe" });
  return { status: result.exitCode, stdout: result.stdout.toString(), stderr: result.stderr.toString() };
}

describe("generated operating-skill chapter contract", () => {
  test("exactly eight chapters own all declarations once, in original order", () => {
    const files = renderManagementSurfaces();
    expect(Object.keys(files)).toEqual(FILENAMES);
    expect(renderManagementSurfaces()).toEqual(files);
    const owned: string[] = [];
    for (const [domain, roots] of Object.entries(GROUPS)) {
      const file = `01_surface_${domain}.md`;
      const text = files[file]!;
      const expected = CAPABILITIES.filter(cap => roots.includes(cap.command[0]!)).map(capabilityInvocation);
      const actual = [...text.matchAll(/^### `?(ocx [^`\n]+)`?$/gm)].map(match => match[1]!);
      expect(actual, file).toEqual(expected);
      expect(text).toContain(`Declared capabilities: ${expected.length}.`);
      expect(files[INDEX]).toContain(`| [${domain}](${file}) | ${expected.length} |`);
      owned.push(...actual);
    }
    expect(owned.sort()).toEqual(CAPABILITIES.map(capabilityInvocation).sort());
    expect(new Set(owned).size).toBe(CAPABILITIES.length);
    const index = files[INDEX]!;
    expect([...index.matchAll(/^### `?(ocx [^`\n]+)`?$/gm)].map(match => match[1]!))
      .toEqual(CAPABILITIES.map(capabilityInvocation));
    expect(index).toContain(`- declared capabilities: ${CAPABILITIES.length}`);
    expect(index).toContain(`- of those, state-changing: ${CAPABILITIES.filter(cap => cap.mutates).length}`);
    expect(index).toContain(`- head-resolved invocations: ${HEAD_CAPABILITIES.length}`);
    for (const text of Object.values(files)) {
      expect(text.split("\n").length - 1).toBeLessThan(2000);
      expect(text.endsWith("\n")).toBe(true);
      expect(new Set(headings(text)).size).toBe(headings(text).length);
    }
  });

  test("shipped references are reachable and every local file+anchor link resolves", () => {
    const files = documents(SKILL_DIR);
    expect(navigationErrors(files, join(SKILL_DIR, "SKILL.md"))).toEqual([]);
    for (const cap of CAPABILITIES) {
      // Canonical CLI tokens are simple words/hyphens: old heading fragments must survive.
      const fragment = capabilityInvocation(cap).replaceAll(" ", "-");
      expect(headings(files[join(SKILL_DIR, "references", INDEX)]!)).toContain(fragment);
      const domain = Object.entries(GROUPS).find(([, roots]) => roots.includes(cap.command[0]!))![0];
      const target = `01_surface_${domain}.md#${fragment}`;
      expect(files[join(SKILL_DIR, "references", INDEX)]).toContain(`](${target})`);
      expect(headings(files[join(SKILL_DIR, "references", `01_surface_${domain}.md`)]!)).toContain(fragment);
    }
  });

  test("secret-returning tasks remain prose handoffs even if usage is accidentally supplied", () => {
    const tasks = ["ocx link issue", "ocx hub invite", "ocx config export"];
    const files = renderManagementSurfaces();
    for (const task of tasks) {
      expect(CAPABILITIES.find(row => capabilityInvocation(row) === task)?.usage).toBeUndefined();
      const owned = Object.values(files).filter(text => text.includes(`### ${task}\n`));
      expect(owned).toHaveLength(2); // index and domain chapter; original anchor retained
      expect(owned.some(text => text.includes("Human-only handoff:"))).toBe(true);
      for (const text of Object.values(files)) {
        expect(text).not.toContain("### `" + task + "`");
        expect(text).not.toContain("Usage: `" + task);
      }
    }
    withGenerator(root => {
      const result = renderFixture(root, `
        for (const row of CAPABILITIES) {
          if (${JSON.stringify(tasks)}.includes("ocx " + row.command.join(" ")))
            row.usage = "ocx " + row.command.join(" ") + " --unsafe-fixture";
        }
      `);
      expect(result.status).toBe(0);
      expect(result.stdout).not.toContain("--unsafe-fixture");
    });
  });

  test("link proof rejects wrong files, wrong fragments and disconnected pages", () => {
    const start = resolve("fixture", "SKILL.md");
    const target = resolve("fixture", "chapter.md");
    expect(navigationErrors({ [start]: "[chapter](chapter.md#ocx-account-pause)",
      [target]: "### `ocx account pause`" }, start)).toEqual([]);
    for (const [link, error] of [["missing.md#ocx-account-pause", "missing file"],
      ["chapter.md#ocx-account-resume", "missing anchor"]]) {
      expect(navigationErrors({ [start]: `[chapter](${link})`, [target]: "### `ocx account pause`" }, start).join("\n"))
        .toContain(error!);
    }
    expect(navigationErrors({ [start]: "No link", [target]: "# Chapter" }, start)).toEqual([`unreachable: ${target}`]);
  });

  test("check detects missing, stale and extra owned chapters without deleting anything", () => {
    withGenerator((root, refs) => {
      const handwritten = join(refs, "01_surface_handwritten.md");
      writeFileSync(handwritten, "# Unrelated handwritten reference\n");
      let result = generate(root, "--check");
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("01_management_surface.md is missing or STALE");
      expect(generate(root).status).toBe(0);
      expect(readdirSync(refs).sort()).toEqual([...FILENAMES, "01_surface_handwritten.md"].sort());
      expect(generate(root, "--check").status).toBe(0);
      const stale = join(refs, "01_surface_accounts.md");
      writeFileSync(stale, "edited\n");
      result = generate(root, "--check");
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("01_surface_accounts.md is missing or STALE");
      rmSync(stale);
      expect(generate(root, "--check").status).toBe(1);
      const extra = join(refs, "01_surface_obsolete.md");
      const previous = `<!-- ${OWNER}. Do not edit by hand. -->\n# Obsolete\n`;
      writeFileSync(extra, previous);
      result = generate(root);
      expect(result.status).toBe(0);
      expect(result.stderr).toContain("Unexpected generated chapter: 01_surface_obsolete.md");
      expect(readFileSync(extra, "utf8")).toBe(previous);
      expect(readFileSync(handwritten, "utf8")).toBe("# Unrelated handwritten reference\n");
      result = generate(root, "--check");
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("Unexpected generated chapter: 01_surface_obsolete.md");
      expect(result.stderr).not.toContain("missing or STALE");
      rmSync(extra); // Fixture-owned cleanup; the generator never removes this file.
      expect(generate(root, "--check").status).toBe(0);
      for (const [file, text] of Object.entries(renderManagementSurfaces())) {
        expect(readFileSync(join(refs, file), "utf8"), file).toBe(text);
      }
    });
  });

  test("optional usage appears beneath unchanged canonical headings only when present", () => {
    withGenerator((root) => {
      const baseline = renderFixture(root, "for (const row of CAPABILITIES) delete row.usage;");
      expect(baseline.status).toBe(0);
      const original = JSON.parse(baseline.stdout) as Record<string, string>;
      expect(Object.values(original).join("\n")).not.toContain("Usage:");
      const result = renderFixture(root, `
        for (const row of CAPABILITIES) delete row.usage;
        Object.assign(CAPABILITIES.find(cap => cap.command.join(" ") === "account pause"),
          { usage: "ocx account pause <provider> <id> [--json]" });
      `);
      expect(result.status).toBe(0);
      const rendered = JSON.parse(result.stdout) as Record<string, string>;
      const usage = "Usage: `ocx account pause <provider> <id> [--json]`\n\n";
      expect(rendered["01_surface_accounts.md"]).toContain("### `ocx account pause`\n\n" + usage);
      rendered["01_surface_accounts.md"] = rendered["01_surface_accounts.md"]!.replace(usage, "");
      expect(rendered).toEqual(original);
    });
  });

  test("rendered flag tables retain enum choices, literal slashes and multiline meanings", () => {
    withGenerator(root => {
      const flags = [
        { name: "--selection", value: "string", summary: "Choose alpha|beta|gamma." },
        { name: "--path", value: "string", summary: "Use C:\\data\\* with left\\|right.\nNext line.\r\nFinal line." },
        { name: "--optional", summary: "No explicit value kind." },
      ];
      const result = renderFixture(root, `Object.assign(CAPABILITIES.find(cap => cap.command.join(" ") === "access key list"), { flags: ${JSON.stringify(flags)} });`);
      expect(result.status).toBe(0);
      const files = JSON.parse(result.stdout) as Record<string, string>;
      const markdown = files["01_surface_access-remote.md"]!.split("### `ocx access key list`\n")[1]!.split("\n### ")[0]!;
      const html = Bun.markdown.html(markdown);
      const rows = [...html.matchAll(/<tr>([\s\S]*?)<\/tr>/g)].map(row =>
        [...row[1]!.matchAll(/<td>([\s\S]*?)<\/td>/g)].map(cell => cell[1]!));
      const flagRows = rows.filter(row => row[0]?.startsWith("<code>--"));
      expect(flagRows).toEqual([
        ["<code>--selection</code>", "string", "Choose alpha|beta|gamma."],
        ["<code>--path</code>", "string", "Use C:\\data\\* with left\\|right.<br>Next line.<br>Final line."],
        ["<code>--optional</code>", "", "No explicit value kind."],
      ]);
    });
  });

  test("unknown roots, duplicate invocations, anchor collisions and oversize chapters fail closed", () => {
    withGenerator((root) => {
      for (const [mutation, message] of [
        ['Object.assign(CAPABILITIES[0], { command: ["future-root"] });', "Unknown surface root: future-root"],
        ['Object.assign(CAPABILITIES[1], { command: CAPABILITIES[0].command });', "Surface anchor collision"],
        ['Object.assign(CAPABILITIES[0], { command: ["account", "a.b"] }); Object.assign(CAPABILITIES[1], { command: ["account", "ab"] });', "Surface anchor collision"],
        ['Object.assign(CAPABILITIES[0], { details: Array(2000).fill("fixture detail") });', "Surface file must stay below 2000 lines: 01_surface_lifecycle.md"],
        ['for (let i = 0; i < 500; i++) CAPABILITIES.push({ ...CAPABILITIES[0], command: ["account", `fixture-${i}`] });', "Surface file must stay below 2000 lines: 01_management_surface.md"],
      ]) {
        const result = renderFixture(root, mutation!);
        expect(result.status).not.toBe(0);
        expect(result.stderr).toContain(message!);
      }
    });
  });
});
