import { describe, expect, test } from "bun:test";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { renderManagementSurface } from "../../scripts/generate-ocx-skill-surface";
import { CAPABILITIES, HEAD_CAPABILITIES, capabilityInvocation } from "../../src/cli/capabilities";
import { CLI_COMMANDS } from "../../src/cli/registry";
import { repoPath } from "../helpers/repo-root";

/**
 * wp8: the repo-owned `ocx` skill.
 *
 * A skill that describes a CLI is a SECOND description of that CLI, free to drift from the first.
 * These tests exist so it cannot: the surface reference is generated and checked, and every command
 * the hand-written pages mention has to exist in the registry.
 *
 * A skill that documents a command nobody can run is worse than no skill, because an agent will
 * try it and conclude the tool is broken.
 */
const SKILL_DIR = repoPath("skills", "ocx");
const SKILL = join(SKILL_DIR, "SKILL.md");
const REFERENCES = [
  "01_management_surface.md",
  "02_json_shapes.md",
  "03_recipes.md",
  "04_failure_semantics.md",
  "05_remote_hub.md",
];

function read(file: string): string {
  return readFileSync(join(SKILL_DIR, file), "utf8");
}

describe("skills/ocx structure", () => {
  test("SKILL.md and every reference exist", () => {
    expect(existsSync(SKILL)).toBe(true);
    for (const ref of REFERENCES) {
      expect(existsSync(join(SKILL_DIR, "references", ref)), ref).toBe(true);
    }
  });

  test("front matter names the skill and carries trigger words", () => {
    const text = readFileSync(SKILL, "utf8");
    expect(text.startsWith("---\n")).toBe(true);
    const front = text.slice(4, text.indexOf("\n---", 4));
    expect(front).toContain("name: ocx");
    expect(front).toContain("description:");
    // Without these it will not activate on the tasks it covers.
    for (const trigger of ["ocx", "opencodex", "account pool", "usage report", "management API"]) {
      expect(front, trigger).toContain(trigger);
    }
  });

  test("SKILL.md routes to every reference it ships", () => {
    const text = readFileSync(SKILL, "utf8");
    for (const ref of REFERENCES) expect(text, ref).toContain(ref);
  });
});

describe("the generated surface reference cannot drift", () => {
  test("the committed file matches regeneration exactly", () => {
    // If this fails, run: bun scripts/generate-ocx-skill-surface.ts
    expect(read("references/01_management_surface.md")).toBe(renderManagementSurface());
  });

  test("it names every declared capability", () => {
    const text = read("references/01_management_surface.md");
    for (const cap of CAPABILITIES) {
      expect(text, capabilityInvocation(cap)).toContain(capabilityInvocation(cap));
    }
    for (const head of HEAD_CAPABILITIES) {
      expect(text, head.invocations[0]).toContain(head.invocations[0]!);
    }
  });

  test("it carries the do-not-edit marker", () => {
    // The marker is the only thing standing between a generated file and a hand-edited one.
    expect(read("references/01_management_surface.md")).toContain("GENERATED by scripts/generate-ocx-skill-surface.ts");
  });
});

describe("documented commands exist", () => {
  /**
   * Every `ocx <word>` that is presented AS A COMMAND, reduced to its top-level name.
   *
   * Only inline code spans and fenced blocks count. Scanning raw prose produced two false
   * positives that are worth remembering: "driving ocx programmatically" (a sentence) and
   * "there is no `ocx request-history` command" -- a line whose entire purpose is to say the
   * command does not exist. A gate that fails on documentation warning you about a missing
   * command is measuring the wrong thing. Inside a code span the string IS a suggested
   * invocation, so the backtick is the signal.
   */
  function documentedCommands(): Set<string> {
    const names = new Set<string>();
    const files = [readFileSync(SKILL, "utf8"), ...REFERENCES.map(r => read(join("references", r)))];
    for (const text of files) {
      const spans: string[] = [];
      // Fenced blocks: everything a reader would copy and run.
      for (const block of text.matchAll(/```[a-z]*\n([\s\S]*?)```/g)) spans.push(block[1]!);
      // Inline code spans, EXCEPT ones a sentence explicitly negates.
      for (const span of text.matchAll(/`([^`\n]+)`/g)) {
        const line = text.slice(text.lastIndexOf("\n", span.index) + 1, text.indexOf("\n", span.index));
        if (/there is no|does not exist|not a command/i.test(line)) continue;
        spans.push(span[1]!);
      }
      for (const span of spans) {
        for (const match of span.matchAll(/\bocx ([a-z][a-z0-9-]*)/g)) names.add(match[1]!);
      }
    }
    return names;
  }

  test("the extractor sees commands inside code, and not command-shaped prose", () => {
    // Guards the gate itself: it must find real invocations, or the assertion below is vacuous.
    const found = documentedCommands();
    for (const expected of ["capabilities", "ready", "status", "logs", "usage", "account", "storage", "inspect"]) {
      expect(found.has(expected), expected).toBe(true);
    }
  });

  test("every ocx <command> named anywhere in the skill is a real command", () => {
    const known = new Set<string>();
    for (const entry of CLI_COMMANDS) {
      known.add(entry.name);
      for (const alias of entry.aliases ?? []) known.add(alias);
    }
    // Head-resolved invocations are not registry entries: they exit before dispatch.
    for (const head of HEAD_CAPABILITIES) {
      for (const invocation of head.invocations) known.add(invocation.replace(/^-+/, ""));
    }

    const unknown = [...documentedCommands()].filter(name => !known.has(name)).sort();
    // A skill that documents a command nobody can run is worse than no skill: an agent will try
    // it and conclude the tool is broken. This is the assertion that caught `ocx request-history`,
    // which the plan named and which does not exist.
    expect(unknown).toEqual([]);
  });
});

describe("the consent boundary is stated, not implied", () => {
  test("SKILL.md forbids starring and does not offer a flag for it", () => {
    const text = readFileSync(SKILL, "utf8");
    expect(text).toContain("Do not star the repository");
    // The failure mode is a skill that mentions the boundary and then hands over a workaround.
    expect(text).not.toMatch(/ocx\s+\S*star\s+--yes/);
  });

  test("no page suggests driving a session-only route another way", () => {
    for (const file of ["SKILL.md", ...REFERENCES.map(r => join("references", r))]) {
      const text = read(file);
      // `gh api` or a raw POST to the star route would be exactly the routing-around this forbids.
      expect(text, file).not.toContain("gh api");
      expect(text, file).not.toMatch(/POST\s+\/api\/github\/star["'`\s]*$/m);
    }
  });

  test("destructive verbs are documented as requiring --yes", () => {
    const skill = readFileSync(SKILL, "utf8");
    const recipes = read("references/03_recipes.md");
    expect(skill).toContain("--yes");
    expect(skill).toContain("no interactive prompt");
    // The preview-first sequence is the operational rule, so it has to appear in the recipes.
    expect(recipes).toContain("PREVIEW");
    expect(recipes).toContain("get approval");
  });
});

describe("access-key recipes keep plaintext outside agent sessions", () => {
  // CLI oracle: access.ts removes one --json before checking exact commit/abort tokens.
  // These canonical spellings are case-sensitive; commit-old-id is a start, not a commit.
  const secretBearingAccessKeyCommand =
    /\b(?:ocx|opencodex)(?:\.(?:exe|mjs|cmd|ps1))?["']?\s+(?:access\s+keys?|api-key)\s+(?:create\b|rotate\b(?!\s+(?:--json\s+)?(?:commit|abort)(?=\s|$)))/gm;
  const secretBearingManagementRequest =
    /(?:(?:\bPOST\b|(?:--request|-X|-Method)\s+["']?POST["']?|method\s*:\s*["']POST["'])[^\n]{0,240}\/api\/keys(?:\/rotate)?(?=$|[\s"'?#])|\/api\/keys(?:\/rotate)?(?=$|[\s"'?#])[^\n]{0,240}(?:\bPOST\b|(?:--request|-X|-Method)\s+["']?POST["']?|method\s*:\s*["']POST["']))/gim;

  /**
   * Early warning for literal recipes in ordinary fences and single-backtick spans.
   * Not a shell/JS parser: implicit POSTs, dynamic calls, alternate Markdown and
   * arbitrary multiline requests remain outside this bounded detector.
   */
  function secretBearingCommandsInCode(text: string): string[] {
    const spans: string[] = [];
    const prose = text.replace(/```[^\n]*\n([\s\S]*?)```/g, (_all: string, body: string) => {
      spans.push(body);
      return "";
    });
    for (const span of prose.matchAll(/`([^`\n]+)`/g)) spans.push(span[1]!);
    const matches: string[] = [];
    for (const span of spans) {
      const executable = span.replace(/(?:\\|`|\^)\r?\n\s*/g, " ");
      matches.push(...Array.from(executable.matchAll(secretBearingAccessKeyCommand), match => match[0]));
      matches.push(...Array.from(executable.matchAll(secretBearingManagementRequest), match => match[0]));
    }
    return matches;
  }

  test("all key aliases reject creation/start and preserve non-secret commit/abort", () => {
    for (const binary of ["ocx", "opencodex"]) {
      for (const group of ["access key", "access keys", "api-key"]) {
        const prefix = `${binary} ${group}`;
        for (const action of [
          "create rotated", "create rotated --json",
          "rotate old-id", "rotate old-id --json", "rotate --json old-id",
        ]) {
          const command = `${prefix} ${action}`;
          expect(secretBearingCommandsInCode("```bash\n" + command + "\n```"), command).toHaveLength(1);
        }
        for (const operation of ["commit", "abort"]) {
          for (const args of [
            `${operation} old-id rotation-id`,
            `${operation} old-id rotation-id --json`,
            `--json ${operation} old-id rotation-id`,
          ]) {
            const command = `${prefix} rotate ${args}`;
            expect(secretBearingCommandsInCode("```bash\n" + command + "\n```"), command).toEqual([]);
          }
          const start = `${prefix} rotate --json ${operation}-old-id`;
          expect(secretBearingCommandsInCode("`" + start + "`"), start).toHaveLength(1);
        }
      }
    }
  });

  test("wrappers, shell continuations and inline examples cannot hide literal commands", () => {
    for (const command of [
      "& ocx access keys create rotated --json",
      "command ocx access key create rotated",
      "env ocx api-key rotate old-id",
      "& 'C:\\Tools\\opencodex.exe' api-key rotate old-id",
      "node /opt/bin/ocx.mjs access key create rotated",
      "ocx.cmd access key create rotated",
      "& './opencodex.ps1' access keys rotate old-id",
      "ocx access key \\\n  create rotated --json",
      "ocx access key `\r\n  create rotated --json",
      "ocx access key ^\n  rotate old-id",
      "ocx access key rotate COMMIT",
    ]) {
      expect(secretBearingCommandsInCode("```bash\n" + command + "\n```"), command).toHaveLength(1);
    }
    expect(secretBearingCommandsInCode("Run `ocx api-key create rotated --json` next.")).toHaveLength(1);
    expect(secretBearingCommandsInCode("Do not run `ocx api-key create rotated --json`.")).toHaveLength(1);
    expect(secretBearingCommandsInCode("Creation under `ocx access key` returns plaintext.")).toEqual([]);
  });

  test("explicit management POST recipes are detected without banning commit or abort", () => {
    for (const route of ["/api/keys", "/api/keys/rotate"]) {
      for (const command of [
        `POST ${route}`,
        `curl -X POST http://127.0.0.1:3000${route}`,
        `curl 'http://127.0.0.1:3000${route}?source=recipe' --request POST`,
        `curl --request POST \\\n  'http://127.0.0.1:3000${route}#example'`,
        `Invoke-RestMethod http://127.0.0.1:3000${route} -Method Post`,
        `Invoke-WebRequest -Method Post http://127.0.0.1:3000${route}`,
        `fetch('${route}', { method: 'POST' })`,
      ]) {
        expect(secretBearingCommandsInCode("```text\n" + command + "\n```"), command).toHaveLength(1);
      }
    }
    expect(secretBearingCommandsInCode("Run `POST /api/keys` next.")).toHaveLength(1);
    for (const command of [
      "ocx access key list --json",
      "ocx access key remove old-id --yes --json",
      "ocx connect rotate --admin-token-stdin --json",
      "curl -X POST http://127.0.0.1:3000/api/keys/rotate/commit",
      "curl -X DELETE http://127.0.0.1:3000/api/keys/rotate",
      "curl -X DELETE http://127.0.0.1:3000/api/keys",
      "curl http://127.0.0.1:3000/api/keys\ncurl -X POST http://127.0.0.1:3000/api/keys/rotate/commit",
    ]) {
      expect(secretBearingCommandsInCode("```bash\n" + command + "\n```"), command).toEqual([]);
    }
    expect(secretBearingCommandsInCode("| POST | `/api/keys/rotate` |")).toEqual([]);
  });

  test("the original unsafe recipe is detected and every shipped page is scanned", () => {
    const original = "```bash\nocx access key list --json\nocx access key create rotated --json\n"
      + "ocx access key remove <old-id> --yes --json\nocx access key list --json\n```";
    expect(secretBearingCommandsInCode(original)).toHaveLength(1);
    for (const file of ["SKILL.md", ...REFERENCES.map(ref => join("references", ref))]) {
      expect(secretBearingCommandsInCode(read(file)), file).toEqual([]);
    }
  });

  test("guidance distinguishes configuration confirmation from revocation authority", () => {
    // Documentation presence/order only: these assertions do not prove agent behavior.
    const skill = readFileSync(SKILL, "utf8");
    const recipes = read("references/03_recipes.md");
    for (const text of [skill, recipes]) {
      expect(text).toMatch(/outside the agent\s+session/);
      expect(text).toMatch(/configuration confirmation is not (?:revocation )?approval/i);
      expect(text).toMatch(/existing explicit\s+approval for that exact revocation remains valid/);
    }
    const approvalAt = recipes.indexOf("separate explicit revocation approval");
    expect(approvalAt).toBeGreaterThanOrEqual(0);
    for (const command of ["ocx access key rotate commit", "ocx access key remove"]) {
      expect(recipes.indexOf(command)).toBeGreaterThan(approvalAt);
    }
  });
});
