import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve, basename } from "node:path";
import { isStandaloneTarget, standaloneExecutableName } from "./standalone-targets";

function hostTarget(): string {
  const platform = process.platform === "darwin" ? "darwin" : process.platform === "win32" ? "windows" : "linux";
  const arch = process.arch === "arm64" ? "arm64" : "x64";
  return `bun-${platform}-${arch}`;
}

function argumentValue(name: string): string | undefined {
  const index = Bun.argv.indexOf(name);
  return index >= 0 ? Bun.argv[index + 1] : undefined;
}

const target = argumentValue("--target") ?? hostTarget();
if (!isStandaloneTarget(target)) {
  throw new Error(`Unsupported standalone target: ${target}`);
}

const repoRoot = resolve(import.meta.dir, "..");
const guiDist = join(repoRoot, "gui", "dist");
if (!existsSync(join(guiDist, "index.html"))) {
  throw new Error("gui/dist is missing; run `bun run build:gui` first");
}

const output = resolve(argumentValue("--out") ?? join(repoRoot, "dist", "standalone", target));
mkdirSync(output, { recursive: true });
const executable = join(output, standaloneExecutableName(target));

// Pre-bundle worker entrypoints so compiled binaries can spawn them from Blob
// URLs: oven-sh/bun#29124 breaks nested worker entrypoints resolved from
// $bunfs, so `new Worker(new URL(...))` dies with ModuleNotFound otherwise.
const WORKER_ENTRIES: Record<string, string> = {
  "policy-worker": join(repoRoot, "src", "storage", "policy-worker.ts"),
  "restore-worker": join(repoRoot, "src", "storage", "restore-worker.ts"),
  "history-worker": join(repoRoot, "src", "codex", "history-worker.ts"),
};
const GEN_FILE = join(repoRoot, "src", "generated", "worker-bundles.gen.ts");
const GEN_PLACEHOLDER = `// Generated by scripts/build-standalone.ts — do not edit by hand.\n// Placeholder for source checkouts; standalone builds overwrite this file\n// with pre-bundled worker sources before compiling.\nexport const WORKER_BUNDLES: Record<string, string> = {};\n`;
const bundleLines: string[] = [];
const workerOut = join(output, ".worker-bundles");
for (const [key, entry] of Object.entries(WORKER_ENTRIES)) {
  const bundled = Bun.spawnSync([process.execPath, "build", entry, "--target", "bun", "--outdir", workerOut], {
    stdout: "inherit",
    stderr: "inherit",
  });
  if (bundled.exitCode !== 0) process.exit(bundled.exitCode ?? 1);
  const name = `${basename(entry, ".ts")}.js`;
  bundleLines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(readFileSync(join(workerOut, name), "utf8"))},`);
}
writeFileSync(
  GEN_FILE,
  `// Generated by scripts/build-standalone.ts — do not edit by hand.\nexport const WORKER_BUNDLES: Record<string, string> = {\n${bundleLines.join("\n")}\n};\n`,
);

// The generated bundles only exist while the compile below consumes them.
// Always restore the empty placeholder afterwards — success or failure — so
// source-checkout runs and tests keep spawning workers from source files
// instead of a stale committed bundle.
function restoreGenPlaceholder(): void {
  writeFileSync(GEN_FILE, GEN_PLACEHOLDER);
}

const compileArgs = [process.execPath, "build", "--compile"];
// Cross-compiling to the host target produces a binary the kernel kills on
// launch; only pass --target when it differs from the host.
if (target !== hostTarget()) compileArgs.push("--target", target);
compileArgs.push(join(repoRoot, "src", "cli", "index.ts"), "--outfile", executable);
// process.exit() skips `finally`, so exit only after the placeholder is back.
let compileExitCode: number;
try {
  compileExitCode = Bun.spawnSync(compileArgs, { stdout: "inherit", stderr: "inherit" }).exitCode ?? 1;
} finally {
  restoreGenPlaceholder();
}
if (compileExitCode !== 0) process.exit(compileExitCode);

// bun's ad-hoc linker signature does not always cover the embedded payload;
// macOS kills the executable on launch (SIGKILL) unless it is re-signed.
if (process.platform === "darwin") {
  const sign = Bun.spawnSync(["codesign", "--force", "--sign", "-", executable], { stdout: "inherit", stderr: "inherit" });
  if (sign.exitCode !== 0) process.exit(sign.exitCode ?? 1);
}

cpSync(guiDist, join(output, "gui", "dist"), { recursive: true });
const digest = createHash("sha256").update(readFileSync(executable)).digest("hex");
writeFileSync(join(output, "SHA256SUMS"), `${digest}  ${executable.split(/[\\/]/).pop()}\n`);
console.log(`Built ${executable}`);
