import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { extname, join, resolve } from "node:path";

export const THRESHOLD = 2000;
export const BASELINE_REL = "tests/fixtures/file-size-baseline.json";

export const SCAN_EXTENSIONS = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".cjs",
  ".mjs",
  ".json",
  ".css",
  ".md",
  ".yml",
  ".yaml",
  ".sh",
]);

export const EXCLUDED_PREFIXES = [
  "devlog/",
  "assets/",
  "docs-site/public/",
  "docs-site/src/assets/",
  "gui/dist/",
] as const;

export const EXCLUDED_EXACT = new Set(["bun.lock", "gui/dist"]);

/**
 * Machine-generated output. Regenerating it is the only way it changes, so a line count is
 * a fact about the generator rather than about anyone's editing habits.
 *
 * Exactly one file qualifies, and it says so on its first line
 * (@generated by protoc-gen-es). The test beside this list reads that banner rather than
 * trusting the name, because "generated" was doing no work here: eleven hand-maintained
 * files sat on this list, and calling them generated is what invites the twelfth.
 */
export const GENERATED_PATHS = [
  "src/adapters/cursor/gen/agent_pb.ts",
] as const;

/**
 * Translation catalogues. Hand-written, and exempt for a different reason: they grow by one
 * line per UI string in ten locales at once, so a cap would block every new string in the
 * GUI rather than any oversized module. gui/src/i18n/en.ts describes itself as the TKey
 * source of truth; nothing generates these.
 */
export const I18N_CATALOG_PATHS = [
  "gui/src/i18n/de.ts",
  "gui/src/i18n/en.ts",
  "gui/src/i18n/fr.ts",
  "gui/src/i18n/ja.ts",
  "gui/src/i18n/ko.ts",
  "gui/src/i18n/ru.ts",
  "gui/src/i18n/tr.ts",
  "gui/src/i18n/vi.ts",
  "gui/src/i18n/zh.ts",
  "gui/src/i18n/zh-TW.ts",
] as const;

/**
 * Hand-maintained data snapshots. Records, not code: their size tracks how much was recorded,
 * and splitting one would hide provenance rather than reduce complexity.
 *
 * model-metadata.source.json is the generator's INPUT, which is why naming it generated was
 * backwards. Its output, src/generated/model-metadata.ts, is 108 lines and is scanned normally.
 */
export const DATA_SNAPSHOT_PATHS = [
  "docs-site/src/data/frontier-benchmarks.json",
  "scripts/model-metadata.source.json",
] as const;

/** Every path exempt from a size cap, whatever the reason. */
export const EXEMPT_PATHS = [
  ...GENERATED_PATHS,
  ...I18N_CATALOG_PATHS,
  ...DATA_SNAPSHOT_PATHS,
].sort() as readonly string[];

export type Verdict =
  | "NEW_OVERSIZED"
  | "GREW"
  | "SHRANK"
  | "EXEMPT"
  | "UNCHANGED"
  | "NEW_OK";

export type Baseline = {
  exempt: string[];
  files: Record<string, number>;
};

export type FileSize = {
  path: string;
  lines: number;
};

export type Evaluation = FileSize & {
  verdict: Verdict;
};

export function countLines(text: string): number {
  return text.split("\n").length - (text.endsWith("\n") ? 1 : 0);
}

export function isScannedPath(path: string): boolean {
  if (EXCLUDED_EXACT.has(path)) return false;
  if (EXCLUDED_PREFIXES.some((prefix) => path.startsWith(prefix))) return false;
  return SCAN_EXTENSIONS.has(extname(path));
}

export function evaluate(files: FileSize[], baseline: Baseline): Evaluation[] {
  const exempt = new Set(baseline.exempt);
  return files.map((file) => {
    if (exempt.has(file.path)) return { ...file, verdict: "EXEMPT" };
    const cap = baseline.files[file.path];
    if (cap === undefined) {
      return { ...file, verdict: file.lines >= THRESHOLD ? "NEW_OVERSIZED" : "NEW_OK" };
    }
    if (file.lines > cap) return { ...file, verdict: "GREW" };
    if (file.lines < cap) return { ...file, verdict: "SHRANK" };
    return { ...file, verdict: "UNCHANGED" };
  });
}

export function isOffender(row: Evaluation): boolean {
  return row.verdict === "NEW_OVERSIZED" || row.verdict === "GREW";
}

export function gitLsFiles(repoRoot: string): string[] {
  const result = Bun.spawnSync(["git", "ls-files"], { cwd: repoRoot });
  if (result.exitCode !== 0) {
    throw new Error(`git ls-files failed: ${new TextDecoder().decode(result.stderr)}`);
  }
  return new TextDecoder()
    .decode(result.stdout)
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);
}

export function scanRepo(repoRoot: string): FileSize[] {
  const out: FileSize[] = [];
  for (const path of gitLsFiles(repoRoot)) {
    if (!isScannedPath(path)) continue;
    out.push({ path, lines: countLines(readFileSync(join(repoRoot, path), "utf8")) });
  }
  return out;
}

export function loadBaseline(text: string): Baseline {
  const raw = JSON.parse(text) as Partial<Baseline> & { generated?: unknown };
  // "generated" was the field's name while it also held i18n catalogues and data snapshots.
  // Reading it as exempt keeps a branch written before the rename loadable instead of
  // failing with a shape error that says nothing about what changed.
  const parsed = {
    ...raw,
    exempt: Array.isArray(raw.exempt) ? raw.exempt : raw.generated,
  } as Baseline;
  if (
    !parsed
    || typeof parsed !== "object"
    || !Array.isArray(parsed.exempt)
    || typeof parsed.files !== "object"
    || parsed.files === null
    || Array.isArray(parsed.files)
  ) {
    throw new Error("invalid file-size baseline");
  }
  return parsed;
}

function sortRecord(input: Record<string, number>): Record<string, number> {
  return Object.fromEntries(
    Object.entries(input).sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0)),
  );
}

export function updateBaseline(current: FileSize[], baseline: Baseline, seed: boolean): Baseline {
  const now = new Map(current.map((file) => [file.path, file.lines] as const));
  const files: Record<string, number> = {};
  for (const [path, cap] of Object.entries(baseline.files)) {
    const lines = now.get(path);
    if (lines === undefined) continue;
    files[path] = Math.min(cap, lines);
  }
  if (seed) {
    const exempt = new Set(baseline.exempt);
    for (const [path, lines] of now) {
      if (exempt.has(path) || lines < THRESHOLD || files[path] !== undefined) continue;
      files[path] = lines;
    }
  }
  return { exempt: [...baseline.exempt], files: sortRecord(files) };
}

export function formatOffenders(rows: Evaluation[]): string {
  return rows
    .filter(isOffender)
    .map((row) => `${row.verdict} ${row.path} ${row.lines}`)
    .join("\n");
}

if (import.meta.main) {
  const repoRoot = resolve(import.meta.dir, "..");
  const baselinePath = join(repoRoot, BASELINE_REL);
  const existed = existsSync(baselinePath);
  const baseline: Baseline = existed
    ? loadBaseline(readFileSync(baselinePath, "utf8"))
    : { exempt: [...EXEMPT_PATHS], files: {} };
  const current = scanRepo(repoRoot);
  if (process.argv.includes("--update")) {
    const next = updateBaseline(current, baseline, !existed);
    writeFileSync(baselinePath, `${JSON.stringify(next, null, 2)}\n`);
    console.log(`wrote ${BASELINE_REL} (${Object.keys(next.files).length} caps)`);
    process.exit(0);
  }
  const offenders = evaluate(current, baseline).filter(isOffender);
  if (offenders.length > 0) {
    console.error("file-size ratchet failed:");
    console.error(formatOffenders(offenders));
    process.exit(1);
  }
  console.log("file-size ratchet passed");
}
