/**
 * Generate the compact operating-skill index and its owned domain chapters.
 * Pure renderers use the public capability facade; I/O stays in the CLI entry point.
 *
 * bun scripts/generate-ocx-skill-surface.ts          # write expected files only
 * bun scripts/generate-ocx-skill-surface.ts --check  # reject missing/stale/extra owned files
 */
import { writeFileSync, readFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { CAPABILITIES, HEAD_CAPABILITIES, capabilityInvocation, type Capability } from "../src/cli/capabilities";

const DIRECTORY = join(import.meta.dir, "..", "skills", "ocx", "references");
const INDEX = "01_management_surface.md";
const OWNER = "GENERATED by scripts/generate-ocx-skill-surface.ts";
const PREAMBLE = `<!-- ${OWNER}. Do not edit by hand. -->\n<!-- Regenerate: bun scripts/generate-ocx-skill-surface.ts -->\n`;

// Navigation groups, not command dispatch. New roots require an explicit assignment.
const DOMAINS = [
  { name: "lifecycle", roots: ["chatgpt", "status", "resolve", "capabilities", "sync", "start", "stop", "restart", "service", "gui"] },
  { name: "providers-models", roots: ["provider", "models", "alias"] },
  { name: "accounts", roots: ["account", "auth", "login", "logout"] },
  { name: "agents-routing", roots: ["agent", "combo", "route", "v2", "effort", "memory"] },
  { name: "integrations", roots: ["claude", "integration", "grok", "codex-shim"] },
  { name: "observe-system", roots: ["companion", "usage", "logs", "storage", "inspect", "system", "observe", "debug", "export", "import", "cost", "update", "config", "tray"] },
  { name: "access-remote", roots: ["link", "remote-workspace", "hub", "connect", "api", "access"] },
  { name: "lab", roots: ["lab"] },
];

function chapterFilename(domain: string): string {
  return `01_surface_${domain}.md`;
}

// GitHub Markdown anchors for canonical CLI headings (backticks are presentation only).
function invocationAnchor(invocation: string): string {
  return invocation.toLowerCase().replace(/[^\p{L}\p{N}_\-\s]/gu, "").replace(/ /g, "-");
}

function assignChapters(): Map<Capability, string> {
  const roots = new Map<string, string>();
  for (const domain of DOMAINS) {
    for (const root of domain.roots) {
      if (roots.has(root)) throw new Error(`Duplicate surface root: ${root}`);
      roots.set(root, chapterFilename(domain.name));
    }
  }
  const assignments = new Map<Capability, string>();
  const anchors = new Set<string>();
  for (const cap of CAPABILITIES) {
    const file = roots.get(cap.command[0]!);
    if (!file) throw new Error(`Unknown surface root: ${cap.command[0]}`);
    const invocation = capabilityInvocation(cap);
    const anchor = invocationAnchor(invocation);
    if (anchors.has(anchor)) throw new Error(`Surface anchor collision: ${invocation} (#${anchor})`);
    anchors.add(anchor);
    assignments.set(cap, file);
  }
  return assignments;
}

// These existing discoverable names return plaintext credentials. Preserve their anchors
// as prose handoffs, never turn them into executable-looking recipes.
const SECRET_HANDOFFS = new Set(["ocx link issue", "ocx hub invite", "ocx config export"]);
function capabilityHeading(invocation: string): string {
  return SECRET_HANDOFFS.has(invocation) ? `### ${invocation}` : `### \`${invocation}\``;
}

function renderIndex(assignments: Map<Capability, string>): string {
  const lines = [PREAMBLE, "# The `ocx` management surface", "",
    "Declared capabilities, grouped by operating task. This index is not every CLI verb.",
    "Read the chapter for routes, flags and mutation notes; use the running binary when versions differ.", "",
    "```bash", "ocx capabilities --json                 # the declared table",
    "ocx capabilities --mutating-only --json  # declared state-changing verbs",
    "ocx capabilities --route /api/logs       # declarations for one route", "```", "",
    "## Resolved before dispatch", "",
    "These answer in the CLI head and never reach the proxy, so they work with nothing running.", "",
    "| Invocation | Purpose |", "|---|---|"];
  for (const head of HEAD_CAPABILITIES) {
    lines.push(`| \`${head.invocations.join("` `")}\` | ${tableCell(head.summary)} |`);
  }
  lines.push("", "## Task chapters", "", "| Chapter | Declared capabilities |", "|---|---|");
  for (const domain of DOMAINS) {
    const file = chapterFilename(domain.name);
    const count = [...assignments.values()].filter(value => value === file).length;
    lines.push(`| [${domain.name}](${file}) | ${count} |`);
  }
  lines.push("", "## Read-only capabilities", "",
    "Read-oriented tasks are marked non-mutating in the registry. Probes may contact providers,",
    "consume quota or refresh caches; this label does not promise cost-free or effect-free execution.", "",
    "## State-changing capabilities", "",
    "Check the chapter's flags, the requested authority and the operating skill's consent and secret rules.", "",
    "## Canonical invocation index", "",
    "Original invocation order. These headings preserve links to the previous single-file reference.", "");
  for (const cap of CAPABILITIES) {
    const invocation = capabilityInvocation(cap);
    lines.push(capabilityHeading(invocation), "",
      `[${cap.mutates ? "State-changing task" : "Read-oriented task"}](${assignments.get(cap)}#${invocationAnchor(invocation)})`, "");
  }
  lines.push("## Counts", "", `- declared capabilities: ${CAPABILITIES.length}`,
    `- of those, state-changing: ${CAPABILITIES.filter(cap => cap.mutates).length}`,
    `- head-resolved invocations: ${HEAD_CAPABILITIES.length}`, "");
  return lines.join("\n");
}

/** Preserve literal prose inside a Markdown table cell, including enum separators. */
function tableCell(value: string | undefined): string {
  return (value ?? "").replaceAll("\\", "\\\\").replaceAll("|", "\\|").replace(/\r\n|[\r\n]/g, "<br>");
}

function renderCapability(cap: Capability): string[] {
  const invocation = capabilityInvocation(cap);
  const handoff = SECRET_HANDOFFS.has(invocation);
  const lines = [capabilityHeading(invocation), ""];
  if (handoff) lines.push("Human-only handoff: ask the operator to perform this in their own terminal or dashboard; do not capture the secret-bearing result.", "");
  if (!handoff && cap.usage !== undefined) lines.push(`Usage: \`${cap.usage}\``, "");
  lines.push(cap.summary, "", `State-changing: ${cap.mutates ? "yes" : "no"}.`, "");
  if (cap.routes.length > 0) {
    lines.push("| Method | Route |", "|---|---|");
    for (const route of cap.routes) lines.push(`| ${route.method} | \`${route.path}\` |`);
  } else {
    lines.push("Drives no management route.");
  }
  lines.push("");
  if (cap.flags.length > 0) {
    lines.push("| Flag | Value | Meaning |", "|---|---|---|");
    for (const flag of cap.flags) lines.push(`| \`${flag.name}\` | ${tableCell(flag.value)} | ${tableCell(flag.summary)} |`);
    lines.push("");
  }
  lines.push(`JSON mode: \`${cap.json}\`.`, "");
  for (const detail of cap.details ?? []) lines.push(`- ${detail}`);
  if ((cap.details ?? []).length > 0) lines.push("");
  return lines;
}

/** Deterministic filename → Markdown map; no filesystem reads or metadata mutation. */
export function renderManagementSurfaces(): Record<string, string> {
  const assignments = assignChapters();
  const files: Record<string, string> = { [INDEX]: renderIndex(assignments) };
  for (const domain of DOMAINS) {
    const file = chapterFilename(domain.name);
    const caps = CAPABILITIES.filter(cap => assignments.get(cap) === file);
    const lines = [PREAMBLE, `# ${domain.name}: declared management tasks`, "",
      `[Management index](${INDEX}) · [Operating rules](../SKILL.md#secret-bearing-commands)`, "",
      "Use these declarations to choose a task, then check its flags and authority before execution.",
      "Non-mutating probes may still contact providers, consume quota or refresh caches.", "",
      `Declared capabilities: ${caps.length}.`, ""];
    if (caps.length === 0) lines.push("No declared capabilities yet. This chapter reserves navigation space; it does not promise a command.", "");
    for (const cap of caps) lines.push(...renderCapability(cap));
    files[file] = lines.join("\n");
  }
  for (const [file, content] of Object.entries(files)) {
    if (content.split("\n").length - 1 >= 2000) throw new Error(`Surface file must stay below 2000 lines: ${file}`);
  }
  return files;
}

/** Compatibility entry point: the compact index, including old fragment forwarders. */
export function renderManagementSurface(): string {
  return renderManagementSurfaces()[INDEX]!;
}

if (import.meta.main) {
  const files = renderManagementSurfaces();
  const extra = readdirSync(DIRECTORY).filter(file =>
    /^01_surface_.*\.md$/.test(file) && !Object.hasOwn(files, file)
    && readFileSync(join(DIRECTORY, file), "utf8").includes(OWNER)).sort();
  for (const file of extra) console.error(`Unexpected generated chapter: ${file}. Review and remove it explicitly; generation never deletes files.`);
  if (process.argv.includes("--check")) {
    const stale = Object.entries(files).filter(([file, content]) =>
      !existsSync(join(DIRECTORY, file)) || readFileSync(join(DIRECTORY, file), "utf8") !== content);
    for (const [file] of stale) console.error(`${file} is missing or STALE.`);
    if (stale.length || extra.length) {
      console.error("Regenerate: bun scripts/generate-ocx-skill-surface.ts");
      process.exit(1);
    }
    console.log(`All ${Object.keys(files).length} generated management surface files are current.`);
  } else {
    for (const [file, content] of Object.entries(files)) {
      writeFileSync(join(DIRECTORY, file), content);
      console.log(`wrote skills/ocx/references/${file}`);
    }
  }
}
