/**
 * Generates `skills/ocx/references/01_management_surface.md` from the capability table.
 *
 * Generated rather than written, because a hand-maintained surface map is a SECOND description
 * of the CLI that is free to drift from the first -- the same defect class this unit removed from
 * the help text. `tests/ci-workflows/skill-ocx.test.ts` asserts the committed file matches this output, so a
 * capability added without regenerating fails CI instead of silently shipping a stale skill.
 *
 * Usage:
 *   bun scripts/generate-ocx-skill-surface.ts            # write
 *   bun scripts/generate-ocx-skill-surface.ts --check     # exit 1 if stale
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { CAPABILITIES, HEAD_CAPABILITIES, capabilityInvocation } from "../src/cli/capabilities";

const TARGET = join(import.meta.dir, "..", "skills", "ocx", "references", "01_management_surface.md");

export function renderManagementSurface(): string {
  const lines: string[] = [];
  lines.push("<!-- GENERATED by scripts/generate-ocx-skill-surface.ts. Do not edit by hand. -->");
  lines.push("<!-- Regenerate: bun scripts/generate-ocx-skill-surface.ts -->");
  lines.push("");
  lines.push("# The `ocx` management surface");
  lines.push("");
  lines.push("Every capability the CLI declares, with the management routes it drives and whether it");
  lines.push("mutates state. This file is generated from the same table `ocx capabilities --json`");
  lines.push("serves, so it cannot describe a command that does not exist.");
  lines.push("");
  lines.push("Ask the running binary instead of trusting this file when the two disagree:");
  lines.push("");
  lines.push("```bash");
  lines.push("ocx capabilities --json                 # the whole table");
  lines.push("ocx capabilities --mutating-only --json  # only state-changing verbs");
  lines.push("ocx capabilities --route /api/logs      # which verbs drive one route");
  lines.push("```");
  lines.push("");

  lines.push("## Resolved before dispatch");
  lines.push("");
  lines.push("These answer in the CLI head and never reach the proxy, so they work with nothing running.");
  lines.push("");
  lines.push("| Invocation | Purpose |");
  lines.push("|---|---|");
  for (const head of HEAD_CAPABILITIES) {
    lines.push(`| \`${head.invocations.join("\` \`")}\` | ${head.summary} |`);
  }
  lines.push("");

  const mutating = CAPABILITIES.filter(c => c.mutates);
  const reading = CAPABILITIES.filter(c => !c.mutates);

  for (const [title, group, note] of [
    ["Read-only capabilities", reading, "Safe to run at any time; none of these change state."],
    ["State-changing capabilities", mutating, "Each of these writes. Check the flags column before running one unattended."],
  ] as const) {
    lines.push(`## ${title}`);
    lines.push("");
    lines.push(note);
    lines.push("");
    for (const cap of group) {
      lines.push(`### \`${capabilityInvocation(cap)}\``);
      lines.push("");
      lines.push(cap.summary);
      lines.push("");
      if (cap.routes.length > 0) {
        lines.push("| Method | Route |");
        lines.push("|---|---|");
        for (const route of cap.routes) lines.push(`| ${route.method} | \`${route.path}\` |`);
      } else {
        lines.push("Drives no management route.");
      }
      lines.push("");
      if (cap.flags.length > 0) {
        lines.push("| Flag | Value | Meaning |");
        lines.push("|---|---|---|");
        for (const flag of cap.flags) lines.push(`| \`${flag.name}\` | ${flag.value} | ${flag.summary} |`);
        lines.push("");
      }
      lines.push(`JSON mode: \`${cap.json}\`.`);
      lines.push("");
      for (const detail of cap.details ?? []) lines.push(`- ${detail}`);
      if ((cap.details ?? []).length > 0) lines.push("");
    }
  }

  lines.push("## Counts");
  lines.push("");
  lines.push(`- declared capabilities: ${CAPABILITIES.length}`);
  lines.push(`- of those, state-changing: ${mutating.length}`);
  lines.push(`- head-resolved invocations: ${HEAD_CAPABILITIES.length}`);
  lines.push("");
  return lines.join("\n");
}

if (import.meta.main) {
  const rendered = renderManagementSurface();
  if (process.argv.includes("--check")) {
    const current = existsSync(TARGET) ? readFileSync(TARGET, "utf8") : "";
    if (current === rendered) {
      console.log("skills/ocx/references/01_management_surface.md is current.");
      process.exit(0);
    }
    console.error("skills/ocx/references/01_management_surface.md is STALE.");
    console.error("Regenerate: bun scripts/generate-ocx-skill-surface.ts");
    process.exit(1);
  }
  writeFileSync(TARGET, rendered);
  console.log(`wrote ${TARGET}`);
}

